### ISSUE TITLE
npm run css:graph2d returns an empty file in dist

### ISSUE THREAD

**Issue by yotamberk** [visjs/vis-timeline#1]
I can't seem to fix the issue and I cant continue without fixing this.
Can you please help me figure what's wrong @mojoaxel ?

**Comment by mojoaxel** [comment]
I'll take a look.

**Comment by mojoaxel** [comment]
Are you planning on providing one big pull request or multiple ones?

**Comment by yotamberk** [comment]
a single one with all the `timeline-plus` features.
I don't see an easy way to do it... I will have to simply try putting in the main files changed and see that nothing broke.

**Comment by mojoaxel** [comment]
@yotamberk Let' talk in [Gitter](https://gitter.im/vis-js/Lobby).

**Comment by mojoaxel** [comment]
see https://github.com/stephentriphahn/concat-glob-cli/issues/2
