### ISSUE TITLE
Group performance by clustering

### ISSUE THREAD

**Issue by jczacharia** [visjs/vis-timeline#10]
I've noticed that having many timeline items drastically decreases performance.

I was attempting to solve this issue and I came across either a forked or different version of Vis.js timeline.

http://almende.github.io/chap-links-library/js/timeline/examples/example16_performance_grouping.html

![performance_grouping](https://user-images.githubusercontent.com/30392170/61663245-2cec3a80-ac9e-11e9-9235-2ccf471c01f5.png)

It appears to be combing or clustering the items to give better performance.

I want to throw this out there because it definitely exists and it would be awesome to see this implemented. I will happily aid in the contribution of this feature.

Here's the main page.
http://almende.github.io/chap-links-library/timeline.html

**Comment by jczacharia** [comment]
I realized that this feature might be included in  merge request https://github.com/visjs/vis-timeline/pull/5

**Comment by jczacharia** [comment]
Thanks to @yotamberk and his https://github.com/yotamberk/timeline-plus, I no longer have performance issues since only the groups visible on the page are rendered. So while I think this feature should still be implemented, the motive behind it (performance issues) have been solved.

**Comment by yotamberk** [comment]
This is now available in this project thanks to #5
