### ISSUE TITLE
How to reverse the sort order of groups (nested)

### ISSUE THREAD

**Issue by payitforwardnow** [visjs/vis-timeline#101]
I'm using the current released version V5. The current documentation available here https://visjs.github.io/vis-timeline/docs/timeline/ indicates I can provide a groupOrder function to sort my groups. If I try to reverse the order they end up scrambled. I've tried to find a solution online and due to the mismatch between the official documentation and the actual behavior I'm struggling to find a solution. Any assistance would be appreciated. 

When the user requests the order to be reversed I simply set a new function for groupOrder. I then reverse it to sort in the other direction. It doesn't work. 

```js
timeline.setOption(
     groupOrder: function(a, b) {
            return b.title < a.title;
     }
}
```

Thank you in advance for your time and consideration.

**Comment by yotamberk** [comment]
I've checked `groupOrdering` example here: https://visjs.github.io/vis-timeline/examples/timeline/groups/groupsOrdering.html 
changing the `groupOrder` property from: `return a.value - b.value;` to `return b.value - a.value;` and everything seems to work fine. Please supply a jsbin showing the problem so I can see the problem you're encountering.
