### ISSUE TITLE
Cannot find namespace 'XSS'

### ISSUE THREAD

**Issue by MassiveHiggsField** [visjs/vis-timeline#1015]
The error i'm getting is:

    Error: node_modules/vis-timeline/declarations/index.d.ts:217:19 - error TS2503: Cannot find namespace 'XSS'.
    
    217   filterOptions?: XSS.IFilterXSSOptions;
    ~~~
    
appreciate the work

**Comment by dennissterzenbach** [comment]
Uhuh. Interesting. I will check that.

**Comment by dennissterzenbach** [comment]
You're right. It seems my local development environment was able to hide that error from me.

I will file a PR later today to fix that. It also looks like there is no point in referencing the namespace here, because js-xss provides the interface IFilterXSSOptions.

Thanks for filing the issue!
