### ISSUE TITLE
Stacking gets turned on when zooming out. 

### ISSUE THREAD

**Issue by payitforwardnow** [visjs/vis-timeline#102]
I'm using the currently released version V5. I set **stack** to false in my options. I have a bunch of statements that appear in the timeline correctly if I zoom out. When I zoom out they all of a sudden get stacked even when they shouldn't . Each "range" item is a month long. The next item starts a day after the proceeding one so there is no reason to stack the items. I've attached screen shots. I've tried setting **stack** to false within each group as well. Am I missing something.  I'm using nested groups if that matters. Why should range items that don't overlap be stacked especially with the stack option set to false. 

![stacked1](https://user-images.githubusercontent.com/30054747/65201067-0ea48000-da3e-11e9-90d4-69c7aa39e1c8.png)

Now if I zoom out just a little bit all of a sudden the items are stacked AND they do not overlap (I checked). 

![stacked2](https://user-images.githubusercontent.com/30054747/65201073-12d09d80-da3e-11e9-94ac-f53b4c79c3cf.png)

Thank you in advance for your time and consideration.

**Comment by javdome** [comment]
Even it looks like a bug in the stack option... For your specific problem, try insert this in your options:
`margin: { item: { horizontal: -1 } }`

And even in your case, you have said:
>  Each "range" item is a month long. The next item starts a day after the proceeding one

So, probably you do not need to set the stack option to false.

**Comment by yotamberk** [comment]
@javdome solution is good. The reason this happens is that in farther zoom out, the margin between items is 0 and since items have borders, They think they are colliding... 
`margin: { item: { horizontal: -1 } }` should do the trick in your case. 
I will close this issue for now unless this solution doesn't work for you and a deeper look needs to be done.
