### ISSUE TITLE
Option to make a custom time marker title editable 

### ISSUE THREAD

**Issue by ryamaguchi0220** [visjs/vis-timeline#105]
Once a custom time marker is added, the custom time marker title can't be edited anymore.
This means that we need to remove and re-add it  to change the title.
I think it would be a good idea to add an option to make a custom time marker title editable.

**Comment by theprometeus** [comment]
I had the same problem, had to do a workaround for it:

1. Add a unique class to the time marker
2. Listen once to the "changed" event
3. Get the DOM element with the given class
4. Change the DOM element title

For example, assuming there is a timeline with var name "timeline", and a dataset with var name "items":
`
const onChange = () => {
timeline.off("changed", onChange);

document.querySelector(".unique-class-name").setAttribute("title", "New element title");
};

timeline.on("changed", onChange);

items.add({
 start: 1,
 end: 5,
 content: "Test",
 className: "unique-class-name"
});
`

**Comment by ryamaguchi0220** [comment]
@theprometeus Thank you for sharing the workaround.
Maybe you mention `the custom time's title` which be set by `setCustomTimeTitle()` ?
This issue mentions `the custom time marker's title` which be added by #86

**Comment by mojoaxel** [comment]
It would be nice to have a custom events that gets fired every time a marker was edited. That way these edits could be saved or something!

**Comment by ryamaguchi0220** [comment]
@mojoaxel  I think too.
I'm going to do it after this issue get resolved.
