### ISSUE TITLE
Scroll when mouse is over the time axis

### ISSUE THREAD

**Issue by smee** [visjs/vis-timeline#109]
Is there a way to have the "zoom on mousewheel" handler of the central timeline element also work while the mouse hovers over the time axis (or axes, if 'both' is set)? Right now the user can only scroll when hovering over the chart contents, but not when hovering over the time axes.

Would it make sense to attach the 'mousewheel' listener from https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L275 to `this.dom.bottom` and `this.dom.top` as well?

**Comment by yotamberk** [comment]
Hi @smee , It seems weird to have a mouse scroll on the time axis to scroll down when the time axis stays unchanged. Don't you think?
You're right about the solution you propose to get your required behavior, but I don;t think it's right for the general use.

**Comment by smee** [comment]
Mmh, my rationale was: Using the mouse wheel while hovering over a timeline triggers the handler (which zooms in/out in my usecase). If the mouse drifts outside of the timeline onto the time axis while still using the wheel the zoom stops.

In my usecase the height of the timeline changes when zooming (due to stacking), which often leads to a vertical shift of the time axis, so it is below the mouse and the zoom stops. If there was a way that I could attach the same mouse wheel listener used on the center element on the time axis, that was useful, imho.

**Comment by yotamberk** [comment]
Why don't you set the timeline to a constant height? Or make the time axis at the top (options with `orientation: 'top'`)
I tend to stay away from the dynamically changing height timeline because it feels weird (especially when the time axis is at the bottom.) since the axis is always moving and it's hard to tell what is the range of the timeline. 
I'm not a UX expert but I would advise one of the two suggestions.
Will these suggestions please your need? Can we close this issue?

**Comment by smee** [comment]
Sure, setting a fixed height will reduce the impact in my specific usecase, but that was not what I meant to say: 
I'm thinking about the user experience when interacting with the timeline: Dragging with the mouse to move the time range works in the center panel as well as on the date axis, but zooming via the mouse wheel only works in the center panel. This feels inconsistent to me from a user experience point of view. The user has to be careful with the mouse position when zooming but not when dragging.

**Comment by yotamberk** [comment]
I've reconsidered what you say and agree that the inconsistency with drag and scroll is not good.
I've added a PR with a fix of this.
