### ISSUE TITLE
Items overlap each other after timeline redraw

### ISSUE THREAD

**Issue by knokit** [visjs/vis-timeline#111]
Range Items with `overflow: visible` are initial stacked properly, however, when calling `timeline.redraw()` they overlap each other.

Here's a test case that reproduces the issue: https://codesandbox.io/s/admiring-bartik-wt0rz

**Comment by yotamberk** [comment]
Can you try the master branch? 
I think I solved it in with #5 .
V6 will be updated soon which should solve many issues.

**Comment by knokit** [comment]
I've tried the master branch and confirm that it solves this issue.
Thanks!

**Comment by yotamberk** [comment]
The next week or so.
I'm closing the issue or do you prefer I wait with closing until the v6 is out?

**Comment by knokit** [comment]
Thank you, @yotamberk !
It can be closed.
