### ISSUE TITLE
Add 'limitSize' as boolean to DataItem's Interface Typings

### ISSUE THREAD

**Issue by micheau-bastien** [visjs/vis-timeline#1127]
Hello,

Using Vis Timeline with TypeScript, I'm have a hard time 'limitSize' option on DataItem. Code like the following will raise typeScript error on limitSize : 
```
const dataItem: vis.DataItem = {
  id: "id",
  group: 0,
  start: new Date(),
  end: new Date(),
  content: "content",
  limitSize: false
}
``` 
Is it possible to add ```limitSize?: boolean;``` to the DataItem's Interface in ```types/index.d.ts```?

Best regards!

**Comment by mojoaxel** [comment]
@micheau-bastien pull-requests are always welcome :wink:
