### ISSUE TITLE
Update GitHub templates

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-timeline#113]
This templates need to be updated:
- [.github/ISSUE_TEMPLATE.md](https://github.com/visjs/vis-timeline/blob/master/.github/ISSUE_TEMPLATE.md)
- [.github/PULL_REQUEST_TEMPLATE.md](https://github.com/visjs/vis-timeline/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

see also https://github.com/fllstx/tgw/pull/9

**Comment by yotamberk** [comment]
Closed with #134 and #133
