### ISSUE TITLE
NPM Install doesn't install types folder in dist

### ISSUE THREAD

**Issue by tylersuchan** [visjs/vis-timeline#118]
I have noticed that when installing vis-timeline through the npm install command, there is no "types" folder (and as a result, no index.d.ts file) that is created. If I clone the repo and built it, however, the types folder is generated. 

I am unsure if that was expected or not, as I'm not too familiar with how npm is supposed to work. I know from prior experience that installing a Typescript version of a npm package is a viable option to fix this, but there is no @types/vis-timeline.

**Comment by Thomaash** [comment]
Hi @tylersuchan and potentially other people who stumble upon this,

the types have been introduced by be8474fb2ee7c0e224f42641f6952d78a3f02efd (September 7) but as of October 2 the latest release is add2f8af97b24ef836a5ac235fd648bfe955b996 (August 2). You can wait for the next release or clone this repo, run `npm ci && npm run build && npm pack` in the repo and then in your project `npm i ./path/to/vis-timeline-0.0.0-no-version.tgz`.

**Comment by mojoaxel** [comment]
@yotamberk is working on the v6 release! I hope it will come out soon!

**Comment by eduboxgithub** [comment]
I'm also waiting for the v6 for this reason.

In the meantime, in my project, every time a do a "npm install" I have to go to the node_modules/@types and duplicate the "vis" folder and rename it to "vis-timeline".

**Comment by yotamberk** [comment]
v6 is now out! This is now solved!
