### ISSUE TITLE
Version 7.4.4 introduce error - visual frame template isn't render correctly

### ISSUE THREAD

**Issue by qubiack** [visjs/vis-timeline#1218]
VisualFrameTemplate doesn't work from version 7.4.4. It was working correctly until the latest version 7.4.9. 

Right now HTML from `visibleFrameTemplate` isn't rendered as HTML but display as a plain text. 
![image](https://user-images.githubusercontent.com/66253914/130911209-aaace0c6-028f-4896-800b-d800108a855e.png)
but it should be visible with visual progress bar:
![image](https://user-images.githubusercontent.com/66253914/130911252-8e27b282-3cb0-432d-be52-2aed05d9fd42.png)

This issue is visible on your example app too:
https://visjs.github.io/vis-timeline/examples/timeline/items/visibleFrameTemplateContent.html - all labels should be displayed.

And live demo on JSFiddle - 7.4.4 with bug:
https://jsfiddle.net/x2eb0yrg/1/

latest version with bug - 7.4.9:
https://jsfiddle.net/x2eb0yrg/3/

And last version 7.4.3 which work correctly:
https://jsfiddle.net/x2eb0yrg/2/

**Comment by clavinovahan** [comment]
This issue is still there in latest release 7.5.1.

**Comment by mojoaxel** [comment]
With #1010 the new option `xss.disabled` was introduced. So if you want to disable the xss checks use this setting!
