### ISSUE TITLE
Style odd /even for days ?

### ISSUE THREAD

**Issue by ChR-iSz** [visjs/vis-timeline#1229]
How i can style odd/even days ?

as example:
odd days -> background-color: white;
even days -> background-color: lightgrey;

**Comment by christau** [comment]
I came accross the same thing and found no answer on how to configure the timeline.  
In the end I helped myself by settin the `className:` of every even item 'odd-days' and of every odd item 'odd-day'.  
But this requires that the groups are sorted with the option `groupOrder: 'id'`

**Comment by ChR-iSz** [comment]
Nice workaround, but it looks like that works only for groups, right ? I search for a solution for the next 20-30 days in horizontal view.

**Comment by mojoaxel** [comment]
Please see this example on how to style even/odd entries:
https://visjs.github.io/vis-timeline/examples/timeline/styling/gridStyling.html
