### ISSUE TITLE
Slow performance in stack function

### ISSUE THREAD

**Issue by tjohnson314** [visjs/vis-timeline#1233]
I tried turning on stacking for a timeline with a few hundred events. But the timeline no longer renders smoothly while I zoom in.

I checked the code, and the stack function is pretty inefficient. Each time it adds a new item, it checks for collisions with every other item. If it finds a collision, it tries shifting the new item to the next row, and checks for collisions with every item again. If the number of rows required is large, that's an O(n^3) algorithm.

There's a greedy algorithm for this that's O(n log n) instead - see the notes on interval partitioning here: https://www.cs.princeton.edu/~wayne/kleinberg-tardos/pearson/04GreedyAlgorithms-2x2.pdf.

If you'd like, I can try fixing this myself and sending a pull request.

**Comment by smee** [comment]
That would be great! Maybe you can get some insights from the previous efforts in this forks PR: https://github.com/yotamberk/timeline-plus/pull/26

**Comment by avbdr** [comment]
Gentlemen, I am interested in resolving this issue and Im up on paying for this improvement. Is anybody available to make a bugfix for this?
