### ISSUE TITLE
Memory leak in setCustomTimeMarker

### ISSUE THREAD

**Issue by Glandos** [visjs/vis-timeline#1245]
In vis-timeline, the [setCustomTimeMarker](https://github.com/visjs/vis-timeline/blob/eaf31b7cd2149373b14c1b8b5326a374edf78d8c/lib/timeline/Core.js#L616) function always create a new marker as a DOM node.

In my use case, I update frequently the same marker, and it creates hundreds of DOM nodes.

Since markers are overwriting each other visually, they should be deleted when setting a new one. It requires to remember the marker node, but it should be easily doable.

**Comment by mojoaxel** [comment]
@jonybekov Contributions are always welcome!

**Comment by Glandos** [comment]
Fixed by #1653
