### ISSUE TITLE
Adding hidden dates to options causes horizontal scroll issues

### ISSUE THREAD

**Issue by data-handler** [visjs/vis-timeline#1282]
* Which vis-component you are referring to: timeline
* Version: 7.5.0
* Browser / OS: Chrome / Mac OS Monterey
* Minimal code example: [jsbin](https://jsbin.com/badoralowa/edit?html,js,output)
* Description of issue:

When supplying hiddenDates array and setting horizontalScroll true, I am experiencing strange zooming when scrolling. i.e. horizontalScroll does not appear to be compatible with hiddenDates option.

**Comment by mojoaxel** [comment]
closing as duplicate of #1243
