### ISSUE TITLE
Add support for strings in Y-axis of Graph2d

### ISSUE THREAD

**Issue by luntta** [visjs/vis-timeline#1292]
Hello,

I'm trying to create a more dynamic version of the famous Marey's graphic train timetable. I would like to use Vis.js for it since I'm already familiar with it and love its performance. However, I noticed that the Graph2d library doesn't support strings as values in the vertical Y-axis.

Would this be a feasible feature to implement?

![marey-schedule-lg](https://user-images.githubusercontent.com/14221637/142221302-aa972fce-7579-4add-8b7d-8e4ccdb78c9d.jpg)

**Comment by mojoaxel** [comment]
> Would this be a feasible feature to implement?

I don't think so 😔
