### ISSUE TITLE
Class attribute of custom html in item content is being omitted

### ISSUE THREAD

**Issue by phofmann** [visjs/vis-timeline#1302]
I was having a look at the following example: https://visjs.github.io/vis-timeline/examples/timeline/items/htmlContents.html
e.g. item4 is being built like `var item4 = 'item <span class="large">4</span>';`

When inspecting the result using chrome dev tool I can only see `<div class="vis-item-content" style="transform: translateX(0px);">item <span>4</span></div>`

In this case the class="large" is being omitted.

The same is happening in my local demo. 
I am using the following versions
"vis-data": "^7.1.2",
 "vis-timeline": "^7.5.0"

Any ideas or help is appreciated.

**Comment by phofmann** [comment]
Well, the solution was already pinned 💯

**Comment by seobrain** [comment]
Attaching here the reference for solution that solves the prolem with classes:
https://visjs.github.io/vis-timeline/examples/timeline/items/htmlContents.html
(just have a look at the source code)
