### ISSUE TITLE
Moveable, zoomable, showMajorLabels are not read from options argument 

### ISSUE THREAD

**Issue by ShinZ6** [visjs/vis-timeline#14]
When creating a new timeline with the options object, moveable, zoomable and showMajorLabels values even though are set to false are not taken in consideration. Other attributes like orientation: 'top' for i.e work fine. Also tested setting this attributes in the example provided in the readme of this repo.

**Comment by smwelch** [comment]
I also have the same issue

**Comment by Nabrok** [comment]
min and max don't work either.

**Comment by yarkm13** [comment]
So many examples didn't work now because of issue

**Comment by ilancohen** [comment]
Fixed in commit #31
