### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-timeline#143]
The cool new example page is broken :disappointed: 
https://visjs.github.io/vis-timeline/examples/timeline/

**Comment by yotamberk** [comment]
@Thomaash Can you please help with this? 
For some reason the screenshots are faulty and give empty images for most cases.

**Comment by Thomaash** [comment]
The example generation ran in parallel with build and therefore didn't have access to dist files. Should be fixed via #146.

**Comment by Thomaash** [comment]
It's works now.
