### ISSUE TITLE
Examples are now all in chinese

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-timeline#144]
I had a look at the examples and the month is all in Chinese. I guess someone changed the default language!?

https://visjs.github.io/vis-timeline/examples/timeline/basicUsage.html

**Comment by yotamberk** [comment]
Fixed with https://github.com/visjs/vis-timeline/commit/2bc69194b2cba5f04d98ec2d6d96f59358c69aae

**Comment by mojoaxel** [comment]
Now all examples are in english! Should the default setting not be the browser default?

**Comment by mojoaxel** [comment]
Also: we should not push to mastet without a pr and a review. Master is protected, but because you are a project owner you can overwrite it 😳
