### ISSUE TITLE
Remove misleading deprecated documentation

### ISSUE THREAD

**Issue by Aaronik** [visjs/vis-timeline#145]
The documentation at https://yotamberk.github.io/timeline-plus/ is still up, and it still appears in google searches. That page is totally broken (as documented here: https://github.com/yotamberk/timeline-plus/issues/185).

This project has two documentation pages. Both show up in searches. One of them is totally broken. That's a bad state of affairs. People will waste their time, think the project has no working docs (because what projects have two separate pages for their docs?).

It would be a kindness to your users to remove that broken page altogether.

Thanks!

**Comment by yotamberk** [comment]
I've removed it now 😄 Thanks!

**Comment by mojoaxel** [comment]
https://yotamberk.github.io/timeline-plus/ is still up

**Comment by Aaronik** [comment]
Interesting, that's still a site with some documentation on the old version, and it probably should also be removed.

However, it's not the original site my complaint was about. That original site had a blue nav on the left and had a routing issue. It was much bigger and more comprehensive though.

**Comment by yotamberk** [comment]
Ok now it should be removed for good.
