### ISSUE TITLE
Examples are not grouped by categories (folders)

### ISSUE THREAD

**Issue by javdome** [visjs/vis-timeline#147]
The new example page is nice... however, the examples are not grouped by categories (the examples folders), and all the examples are listed by alphabetic order.
I have seen that it does not happen in the network example page. There, the examples are group by the folders (Data, Edge styles, etc...).

Could the examples be grouped as well by their folders??

Thanks!!

**Comment by Thomaash** [comment]
Hi @javdome and anyone else interested,

grouping the examples is very simple. It's just necessary to change the titles in the example HTML files which at the moment look like `<title>Timeline | Example Name</title>` to `<title>Timeline | Group Name | Example Name</title>` or `<title>Timeline | Group Name | Subgroup Name | Example Name</title>` etc. The rest will be taken care of by the CI.

**Comment by yotamberk** [comment]
Fixed with #155
