### ISSUE TITLE
attribute d: Expected number

### ISSUE THREAD

**Issue by mgobishop** [visjs/vis-timeline#15]
I'm using Graph2d. Not sure if this is an issue or my own stupidity but I get the following error:

Error: <path> attribute d: Expected number, "M522,NaN CNaN,NaN NaN…".

My code looks like:

```js
this.data = {
  groups: new V.DataSet([]),
  items: new V.DataSet([])
};
this.data.groups.update([
  { id: 1, content: 'A', options: {
    drawPoints: false
}},
{ id: 2, content: 'B', options: {
    drawPoints: false
  }}
]);
this.data.items.update([
  { x: new Date('2014-06-13'), y: 10, group: 1 },
  { x: new Date('2014-06-14'), y: 20, group: 1 },
  { x: new Date('2014-06-21'), y: 20, group: 2 },
  { x: new Date('2014-06-25'), y: 30, group: 2 }
]);
let container = document.getElementById("chart");
let options = {
  start: new Date('2014-06-10'),
  end: new Date('2014-07-04'),
  legend: true,
  height: '100%',
  autoResize: true,
  clickToUse: true
};
this.c = new V.Graph2d(container, this.data.items, this.data.groups, options);
```
Any ideas?

**Comment by mojoaxel** [comment]
This problem is the 
```js
height: '100%',
```

For a height in percentage to work you need to set the height of the parent element. In you case the following css should do the trick:
```css
body: {
  height: 100%;
}
#chart: {
  height: 100%;
}
```

**Comment by mojoaxel** [comment]
We propably should add some error-handling here...

**Comment by mgobishop** [comment]
Thanks for the response. I've changed the height in the css, removed all mentions of height, set everything to height in pixels but all with no luck. I still get the error?

**Comment by mojoaxel** [comment]
@mgobishop Sorry but the problem is in your code!
Here is an working example:
https://jsbin.com/pibatuc/edit?html,output

**Comment by mgobishop** [comment]
Hi. I have now fixed this. I had overridden the following styles and this caused the failure!

.vis-up {
	display: none !important;
}
.vis-down {
	display: none !important;
}
.vis-left {
	display: none !important;
}
