### ISSUE TITLE
Negative (BC) dates do not display properly

### ISSUE THREAD

**Issue by gavinr** [visjs/vis-timeline#1505]
Minimal demo case: 
https://jsbin.com/tohumelazu/3/edit?html,output

```
var items = new vis.DataSet([
    {id: 1, content: 'item 1', start: new Date('0050-04-20'), end: new Date('500-04-20')},
    {id: 2, content: 'item 2', start: new Date('-0050-04-20'), end: new Date('-0020-04-20')},
  ]);
```

- Expected: "Item 2" should be just to the left of the "0" year
- Actual: "Item 2" is not on the timeline - fixed to left-side

![image](https://user-images.githubusercontent.com/209355/183819092-8a3db732-997a-471d-81b0-8e697e80a60f.png)

Is there a better way to display BC dates?

**Comment by scriptkiddielvl2** [comment]
Try adding '00' in front of (negative) dates like : -000050-04-20.

**Comment by scriptkiddielvl2** [comment]
The 'expanded year feature' aka 'leading zeros trick' is needed when your data range is out of the default range for years : 0 - 9999.
As far as my understanding goes, the 'deep' reason is JS using IS08601 specification for date management.
More human friendly documentation can be found below :
https://tc39.es/ecma262/#sec-expanded-years
https://momentjs.com/docs/#/displaying/
Happy to help
