### ISSUE TITLE
Timeline: Cannot use typescript > 4.7

### ISSUE THREAD

**Issue by Valentin-MF** [visjs/vis-timeline#1530]
I import vis-data and vis-timeline into a typescript application. Since I upgraded Typescript from 4.7.x to 4.8.x, I get this error:
![image](https://user-images.githubusercontent.com/114172196/191979229-9de077e1-2274-498e-a24e-05e88cdde220.png)

**Comment by MarianaMaksymiv-Driivz** [comment]
Have the same error? Do we have a solution?

**Comment by Mariissa** [comment]
Have the same error, do we have a solution?

**Comment by Valentin-MF** [comment]
While waiting for a correction I don't use the types from the library anymore.

**Comment by Mariissa** [comment]
From where you take your imports?

**Comment by Valentin-MF** [comment]
It depends on your project. I use angular so I added the standalone scripts in the scripts section of angular.json and in the typescript I don't import anything from the library, I just use globalThis.vis. 

Like this:

angular.json:
```      
...
    "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "scripts": [
              "./node_modules/vis-data/standalone/umd/vis-data.min.js",
              "./node_modules/vis-util/standalone/umd/vis-util.min.js",
              "./node_modules/vis-timeline/standalone/umd/vis-timeline-graph2d.min.js"
            ]
          },
...
```

Usage in my angular component:
`let timeline = new globalThis.vis.Timeline(...)`

**Comment by Mariissa** [comment]
Cool, I am using Angular too, just made the upgrade and got this errors.  Could you explain me please how do you declare vis inside globalThis?

**Comment by Valentin-MF** [comment]
Nothing to do. It's done in the standalone version.

**Comment by BoJIbFbI4** [comment]
Hi, [Valentin-MF](https://github.com/Valentin-MF), can u show ur typings/global.d.ts ? it's will help me a lot.

**Comment by Valentin-MF** [comment]
I don't have global.d.ts

**Comment by Valentin-MF** [comment]
You may need to remove noImplicitAny in your tsconfig.json.

**Comment by slavede** [comment]
I have also changed code not to use the typings now and importing raw .js, but in my opinion, it's not the best solution.

It would be great if this gets in somehow, just typing update is needed I believe.

**Comment by duckyb** [comment]
Another possible workaround is to add:
`"skipLibCheck": true,` to your `tsconfig.json`

**Comment by slavede** [comment]
But this would apply it for every lib, I really wouldn't like that.

**Comment by jonybekov** [comment]
Any workarounds?

**Comment by Valentin-MF** [comment]
Since the latest version of vis-util (https://github.com/visjs/vis-util/releases/tag/v5.0.6) and after adding the `@egjs/hammerjs` package (2.0.17) to my `devDependencies`, my typescript compilation no longer encounters errors.
