### ISSUE TITLE
When Time Line bars dragging and dropping then milestones connections are not moving as per time line bar ?

### ISSUE THREAD

**Issue by Rajendra-dev** [visjs/vis-timeline#154]
Hello,

We added project groups and milestones on it and also we connecting milestones using arrows.
Now on move project, Milestones not moving with the project group.

For a better understanding of this issue we created a demo plunker. 
Please find below the URL and follow below steps to re-generate the same issue.

Pulnker URL:
https://plnkr.co/edit/sHDVIK4lPjW34So4esIa?p=preview

Screenshot:- 1. On Page Load, Showing Correctly
![image](https://user-images.githubusercontent.com/56907639/67477608-11674600-f678-11e9-9518-4995301cc109.png)

Screenshot:- 2. Moving Project bar but milestone not moving with project bar
![image](https://user-images.githubusercontent.com/56907639/67477833-79b62780-f678-11e9-98a9-d0f0ee474d2d.png)

**Comment by yotamberk** [comment]
I don't understand the issue. You connected point items to point items and want to do what with them?
