### ISSUE TITLE
Subgroups overlap when scrolling vertically

### ISSUE THREAD

**Issue by jczacharia** [visjs/vis-timeline#156]
Scrolling up and down causes subgroups to overlap until you zoom in/out or you scroll up and down twice.

Preconditions:
* Enough groups to induce a vertical scroll bar
* At least 2 subgroups per group
* stacking disabled

Demo:
![defect_subgroupoverlay](https://user-images.githubusercontent.com/30392170/67577819-3b1f7c00-f70f-11e9-8a66-1513e96b66ec.gif)

**Comment by yotamberk** [comment]
Closed with #157
