### ISSUE TITLE
Two error in node_modules: moment and hammerjs have no default export

### ISSUE THREAD

**Issue by chiruko** [visjs/vis-timeline#160]
Hello,

I installed vis-timeline on my project today and it works correctly, but I had the follow issues: 

"ERROR in node_modules/vis-timeline/dist/types/index.d.ts(31,8): error TS1192: Module '".../node_modules/moment/moment"' has no default export.
    node_modules/vis-timeline/dist/types/index.d.ts(33,8): error TS1192: Module '"hammerjs"' has no default export. "

I solved this issue by modifying two things in index.d.ts:
- from import moment from 'moment'; to import * as moment from 'moment';
- from import Hammer from 'hammerjs'; to import * as Hammer from 'hammerjs';

Could you please fix this issue so we can share our projects with our mates?

Thanks a lot.

**Comment by sid69330** [comment]
Hello,

The allowSyntheticDefaultImports (set to true) build option resolves the build for me.

**Comment by chiruko** [comment]
> Hello,
> 
> The allowSyntheticDefaultImports (set to true) build option resolves the build for me.
> 
> `"compilerOptions": { "allowSyntheticDefaultImports": true }`



Thanks a lot that worked for me ! If someone wonders where is this "compilerOptions" : it's in the tsconfig.json file.
