### ISSUE TITLE
Changing custom time marker's title results in multiple divs added to the page

### ISSUE THREAD

**Issue by bpfoster** [visjs/vis-timeline#1652]
If I add a custom time to the timeline, add a marker to it, and then want to change the marker's title, a new div `vis-custom-time-marker` is added to the DOM each time I call `setCustomTimeMarker()`, and none of them are cleaned up until I remove the custom time.

The workaround would be to destroy and re-create the custom time every time I want to change the marker text, but I believe the API should allow this use case and not create potentially lots of junk objects in the DOM.

Simple reproduction:
```
var container = document.getElementById('visualization');
var items = new vis.DataSet();
var customDate = new Date();
var options = {
  start: new Date(Date.now() - 1000 * 60 * 60 * 24),
  end: new Date(Date.now() + 1000 * 60 * 60 * 24 * 6)
};
var timeline = new vis.Timeline(container, items, options);

var marker = undefined;

timeline.on('mouseMove', (properties) => {
  if (!marker) {
    marker = timeline.addCustomTime(properties.time, 'mouse-time-bar');
    timeline.setCustomTimeTitle('', marker);
  } else {
    timeline.setCustomTime(properties.time, marker);
  }
  timeline.setCustomTimeMarker(properties.time, marker, false);
});
```

**Comment by Glandos** [comment]
Congrats, you also fix #1245 :+1:
