### ISSUE TITLE
Feature request: Option to not stack items when one's end date is the same as another's start date.

### ISSUE THREAD

**Issue by MartinManev** [visjs/vis-timeline#166]
I work only with dates (all times are set to either 0:00 or 12:00). When one item's end date is the same as another's start date (or close enough), then they will become stacked, but I don't want them to become stacked - only if there is actual overlap.

I don't want to disable the stacking feature entirely as I also have need for it.

Is it possible to achieve this in any other way?

**Comment by zangrossig** [comment]
Maybe it would be useful a distance range parameter, for stacking or not the items.

**Comment by tomberek** [comment]
`options.margin.item.horizontal = 0`

**Comment by MartinManev** [comment]
@tomberek's solution works! Thank you.
