### ISSUE TITLE
[Feature] Option to change position of timeline components.

### ISSUE THREAD

**Issue by supSugam** [visjs/vis-timeline#1674]
I think there should be an option to change the position of items. I want to change the position of date view at the bottom to top, and items container below it. I tried manipulating css/styles but it didn't worked out well. So, please consider it.

**Comment by esemplare** [comment]
Check the docs, look at `orientation` under https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options.

**Comment by supSugam** [comment]
> Check the docs, look at `orientation` under https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options.

My bad, I didn't go through the docs properly, thank you so much.
