### ISSUE TITLE
Timeline, Range Item: Cannot increase or decrease duration when setting editable.updateTime on individual item

### ISSUE THREAD

**Issue by MartinManev** [visjs/vis-timeline#168]
If the timeline option `editable.updateTime` is set to `true`, then all items can be moved horizontally (change their dates) and range items specifically can also be prolonged or shortened. An example of this can be seen here: https://visjs.github.io/vis-timeline/examples/timeline/editing/editingItemsCallbacks.html
The source code of the example has:
```javascript
var options = {
  editable: true,
  ...
```
But even if you change it to the following the result is still the same:
```javascript
var options = {
  editable: {
    updateTime: true,
  },
  ...
```

### The problem

The problem is I don't want to set the editable option globally and instead want to set it on individual items.

If I do:
```javascript
rangeItem.editable = {
  updateTime: true,
};
```
Or even:
```javascript
rangeItem.editable = true;
```
Then I can only move the range item on the timeline, but I cannot prolong or shorten its duration.

Here is a reproduction link, where the timeline option `editable` is set to `false`, but the range items property `editable` is set to `true`:
https://jsfiddle.net/wr8jvons/

### What I want to happen

I think it would be best if this feature is not integrated into the `editable.updateTime` property, but instead has its own properties. For example: `editable.updateStart` and `editable.updateEnd`. This is actually what I'll need for my project.

**Comment by yotamberk** [comment]
It can be done. 
Checkout: https://visjs.github.io/vis-timeline/examples/timeline/editing/individualEditableItems.html
