### ISSUE TITLE
"infinite loop in redraw" warning on browser zoom

### ISSUE THREAD

**Issue by Waddas** [visjs/vis-timeline#17]
I'm using the VisJs timeline from the 'almende/vis' repo and come across an issue where if you change the zoom level (80% causes the most problems) then the redraw function gets stuck in a infinite loop. There is a repeated warning in the console 'WARNING: infinite loop in redraw?'.

There is an issue raised in the old repo: [Timeline Issue: Sometimes the redraw cycle can become stuck in an infinite loop #450
](https://github.com/almende/vis/issues/450)

I've gone through the examples for this repo and i can see is it still occurring. If the old issues are still being tracked then i apologise and feel free to close this one.

**Comment by mojoaxel** [comment]
@Waddas Thanks for re-reporting this issue. @yotamberk is working (see #5) on the next big release that will fix a lot of issues. We'll see if this problem still exists after the merge.

**Comment by javdome** [comment]
I think it will no fix the problem... the same issue was recently opened in Timeline-plus  https://github.com/yotamberk/timeline-plus/issues/175

You can also see more information there.

**Comment by molkemon** [comment]
I am experiencing this issue aswell (with the soon to be merged timeline-plus). I don't have browser zoom on, what I am trying to do is load the timline inside a div within a DataTables Cell. 

It flat out doesn't work, after getting item data via ajax the error message repeats itself a few times and then it just outputs "0" as text. No graph at all. 

I also get another warning in console:
` Something is wrong with the Timeline scale. Limited drawing of grid lines to 1000 lines.`

**Comment by yotamberk** [comment]
Can you supply a simple jsbin so I can try to fix this with a reproducible eample?

**Comment by Waddas** [comment]
@yotamberk Not sure what json you would want to see. If you use the basic example https://visjs.github.io/vis-timeline/examples/timeline/basicUsage.html and reduce the browser zoom to 80%. then resize the browser, you should see the warning in the console.

**Comment by mojoaxel** [comment]
@Waddas Thanks. I can confirm this.

**Comment by mojoaxel** [comment]
Wow, this is an old bug! see https://github.com/almende/vis/issues/450 for more history!

**Comment by frankdevryer** [comment]
Is there any update on this issue?
