### ISSUE TITLE
[Feature Request] Show all the group items on the same line

### ISSUE THREAD

**Issue by GabrielGonMorais** [visjs/vis-timeline#1770]
Hi! Well, working with the vis-timeline, I see the items distribution look like this:
<img width="1133" alt="Captura de Tela 2024-02-28 às 18 09 07" src="https://github.com/visjs/vis-timeline/assets/91505442/dbac8c69-c95c-4677-8ed2-9fd66715d7b7">

But, I would love to see the items like this:
<img width="1133" alt="Captura de Tela 2024-02-28 às 18 08 27" src="https://github.com/visjs/vis-timeline/assets/91505442/ffd5820d-2b0a-4e0c-bda7-2da4f4509ef6">

I tried to put these three items on the same line with css, but groups height still large. To fix it, I would have to change all the timeline structure.

The expected result would be like this:
<img width="1133" alt="Captura de Tela 2024-02-28 às 18 14 33" src="https://github.com/visjs/vis-timeline/assets/91505442/c0a8c19c-ef37-4195-90e3-8c3520418d89">

Could this be a featuring? 

Thank you guys!

**Comment by alexdeia** [comment]
Hi! 
Stack option in **Configuration Options** is not the same?
 
stack | boolean | true | If true (default), items will be stacked on top of each other such that they do not overlap.
-- | -- | -- | --

**Comment by GabrielGonMorais** [comment]
> Hi! Stack option in **Configuration Options** is not the same?
> 
> stack	boolean	true	If true (default), items will be stacked on top of each other such that they do not overlap.

unfortunately doens't work (value 'pt' in the locale parameter doens't work too)
<img width="610" alt="Captura de Tela 2024-02-29 às 09 52 24" src="https://github.com/visjs/vis-timeline/assets/91505442/33ff865f-f28d-4a86-8943-685c735a5913">
![Captura de Tela 2024-02-29 às 09 52 14](https://github.com/visjs/vis-timeline/assets/91505442/4e676fde-4505-4f9d-8855-26bf0e5be870)

version: "vis-timeline": "7.7.3"

**Comment by alexdeia** [comment]
Why do you use true value for stack? It is a default value. So in your screenshot the tasks are really stacked.

Try 
```ts
const timelineOptions = {
  stack: false
}
```
Official example from documentation https://visjs.github.io/vis-timeline/examples/timeline-generated/codepen.cd241505bf80e03e6b96c4b8aa197e6b07591e7162df44cd75e72362318f3e0f.html

<img width="1004" alt="image" src="https://github.com/visjs/vis-timeline/assets/1095051/40b70f08-5bcb-4fb0-85b2-3d91610e6eae">


About locale - pt-BR works.

<img width="836" alt="image" src="https://github.com/visjs/vis-timeline/assets/1095051/780edd96-0e75-4485-b8cd-e6c64bbab5c2">

Just use moment locale like this:

```ts
import 'moment/dist/locale/pt-br.js'

const timelineOptions = {
  moment(date: Date) {
    moment.locale('pt-BR')

    return moment(date)
  },
}
```

You don't have to change the locale prop in timeline options.

**Comment by GabrielGonMorais** [comment]
Thank You! @alexdeia
