### ISSUE TITLE
[BUG] Some (large) items doesn't show up on horizontal scrolling

### ISSUE THREAD

**Issue by gmcinalli** [visjs/vis-timeline#180]
Replicable here: https://visjs.github.io/vis-timeline/examples/timeline/

Extend the `Order 251`'s start to 10:00 AM, after this, do as follows:

![Vis-Bug](https://user-images.githubusercontent.com/9024983/68599924-cd5ea880-04a1-11ea-8327-6c31dda1bf06.gif)

Why does the `Order 251` item appear after a certain threshold, Is this a normal behavior or a bug?

This occurs only with particularly large items.

**Comment by gmcinalli** [comment]
Any updates on this?

**Comment by kevinoshea** [comment]
Having the same issue. Managed to workaround it by having an event handler on rangechanged and calling setGroups in there (with the same data that had already been previously set) - this seems to trigger something that causes it to render correctly.

**Comment by Simondin** [comment]
@kevinoshea I have the same problem and I tried your solution, but it seams not working. Only forcing the  setItems on Vis works. Can you please send to me your snippet?

**Comment by kevinoshea** [comment]
@Simondin using either setGroups or setItems seems to work in my case. In fact setItems might be better anyway. Sorry I don't really have a nice snippet on hand that I can send. It would be good to dig through these functions to see if we can find out how the rendering is being corrected. That might reveal a better solution/workaround.

**Comment by gmcinalli** [comment]
@yotamberk Do you have something to tell us about it?

**Comment by yotamberk** [comment]
I'll take a look at this. Weird...

**Comment by gmcinalli** [comment]
@yotamberk Thank you so much, keep us updated!

**Comment by gmcinalli** [comment]
a

**Comment by gmcinalli** [comment]
@yotamberk Any updates on this?

**Comment by KalleKalkun** [comment]
@yotamberk Any updates on this issue?

**Comment by yotamberk** [comment]
Not yet. I'm not available too much to deal with this issue.
