### ISSUE TITLE
Text in dynamic content does not float during horizontal scroll

### ISSUE THREAD

**Issue by yuz302** [visjs/vis-timeline#182]
As you scroll the timeline to the right, the header of an item would float to stay visible in the timeline but the label in a dynamic content does not stay, which is not consistent. Is there a workaround?

<img width="655" alt="Screen Shot 2019-11-11 at 8 04 50 PM" src="https://user-images.githubusercontent.com/16616564/68641256-27219b80-04bf-11ea-9b31-997e5e61daf0.png">

**Comment by yotamberk** [comment]
This is the difference between `visibleFrameTemplate` and the content of the item. Whilst the item content is always visible and floats with the frame of the timeline (as much as it the item fits, the `visibleFrameTemplate` is in respect to the real item and will not float with the timeline visible frame. In retrospect, the name of the option is not very good... It is kind of counter intuitive to what it's meant to do.
