### ISSUE TITLE
Memory Leak in Group Event Registration (via timeline.setGroups()/timeline.setData())

### ISSUE THREAD

**Issue by aphix** [visjs/vis-timeline#183]
### Fiddle/Example

Use the 'Memory' tab in your browser's developer tools to watch the memory usage over time.
In the below example I see ~65,000 callbacks and ~90mb memory usage after 60 seconds. 

![image](https://user-images.githubusercontent.com/831537/68722349-2b16f180-0583-11ea-9e5e-a18c3c0bacdc.png)

[Here's a complete JS Fiddle demonstrating the leak](https://jsfiddle.net/6gye51v7/1/).

Line 52 is causing the leak in the above example.

### Description/Analysis

The leak occurs when calling `timeline.setGroups` (or `timeline.setData`) with any number of groups.

The number of items does not appear to affect this, and this issue does not appear to occur simply when setting items, or redrawing, only when using either setGroups or setData to set new groups.

The issue appears to be in `Group.js` when registering a listener to check for ranged items:

`itemSet.body.emitter.on("checkRangedItems", ...fn...)` is called on all groups, ignoring whether or not the listener has already been registered on the emitter, leading to a leak of unreleased listeners.

In current revision: [Group.js, lines 85-87](https://github.com/visjs/vis-timeline/blob/9fc7c3d950dae1134e290929b829c5c660c37554/lib/timeline/component/Group.js#L87-L89)

[This bug was introduced 5 years ago in this commit](https://github.com/visjs/vis-timeline/commit/67711304a7c4e6b19ab192e7933e074e499e7068#diff-f4d829b4f8b61a3d664fc7a5eb70924dR35-R37)

### Hacky Workaround

Simply `delete timeline._callers.checkRangedItems` before redrawing or setting new data.

### Next Steps

I'm not familiar enough with the library to comfortably submit a PR without knowing the ramifications of the change (or if there are other things that rely on this behavior), however if it will greatly increase the speed of getting this fixed and merged, then perhaps I can spend some time over the next week to create a suitable patch.

Please let me know if you have any other questions, if there is trouble reproducing, or if I need to provide any other details.

Thanks,
Aphix

**Comment by tmalatinszki** [comment]
Hi,

Are there any plans to have it fixed in one of the upcoming releases? If not, is there any way to apply the mentioned workaround if I am using ngx-vis?

Thanks,
Tamás
