### ISSUE TITLE
Multiple Typescript Errors when trying to build with webpack

### ISSUE THREAD

**Issue by tylersuchan** [visjs/vis-timeline#185]
Whenever I try to run any of the following webpack scripts,
`webpack --watch` 
`webpack --config webpack.prod.js`

I am greeted with a slew of Typescript errors:
`ERROR in node_modules/vis-util/dist/types/util.d.ts(214,52): TS2304: Cannot find name "readonly".`
`ERROR in node_modules/vis-util/dist/types/util.d.ts(214,61):TS7006: Parameter 'T' implicitly has an 'any' type.`
`ERROR in node_modules/vis-util/dist/types/util.d.ts(215,55): TS2304: Cannot find name "readonly".`
`ERROR in node_modules/vis-util/dist/types/util.d.ts(215,64): TS7006: Parameter "A" implicitly has an "any" type.`
`ERROR in node_modules/vis-util/dist/types/util.d.ts(223,43): TS2304: Cannot find name "readonly".`
`ERROR in node_modules/vis-util/dist/types/util.d.ts(223,52): TS7006: Parameter 'T' implicitly has an 'any' type.`
I am able to render what I need to (I made a React Wrapper around the vis-timeline library), but I require the prod webpack build to be successful in order to use the library. I am also unsure if this is an error on the library side, or if there's a package-dependency issue going on. Has anyone else run into this issue?

**Comment by Thomaash** [comment]
Hi @tylersuchan,

what version of tsc are you using? We use quite recent tsc (3.6) and since TypeScript is improving type inference with every version and readonly is also not that old updating may resolve these issues. If not we should probably move this to https://github.com/visjs/vis-util and continue investigating it there.

**Comment by rajputvai** [comment]
Upgrading TypeScript has fixed the issue for me.

**Comment by tylersuchan** [comment]
@rajputvai had the same situation as me. I had typescript@3.1.6, moving up to @3.7.2 fixed it. Thank you!
