### ISSUE TITLE
[Question] Are the min files no longer provided?

### ISSUE THREAD

**Issue by ryamaguchi0220** [visjs/vis-timeline#186]
Hi,

I'm using vis-timeline via a cdn like https://cdn.jsdelivr.net/gh/visjs/vis-timeline@6.0.0/dist/vis-timeline-graph2d.min.js. However, the min files seem to be not provided from v6.0.1

**Comment by exoego** [comment]
At least, latest (v6.2.0) provides min.
https://cdn.jsdelivr.net/npm/vis-timeline@6.2.0/dist/vis-timeline-graph2d.min.js

**Comment by ryamaguchi0220** [comment]
Thanks!

**Comment by kuehn-sba** [comment]
I need an **unminified** build. Where to find (like in the original almende version)!?
