### ISSUE TITLE
Please attach an unminified/uncompressed rollup config (without terser)

### ISSUE THREAD

**Issue by kuehn-sba** [visjs/vis-timeline#197]
I build the dist with:
npm run-script build

But I can't find an **unminified** build. I really need it. Can you please add a terser free build? (as it was also available in the original almende version)

**Comment by mojoaxel** [comment]
We support *.map files. If you really need an unminified version you have to build your own version. Just remove the [terser plugin from rullup.config.js](https://github.com/visjs/vis-timeline/blob/master/rollup.config.js#L73-L77).
