### ISSUE TITLE
Timeline.focus should only zoom in by option/param

### ISSUE THREAD

**Issue by kuehn-sba** [visjs/vis-timeline#198]
Someone had suggested "focus should zoom" and it was simply merged in the past (without being able to turn it off.):

https://github.com/almende/vis/pull/4038

But I don't like that autozoom in! it is very annoying when an item is focused and additionally zoomed in.

This change is also not in the last vis version of almende (4.21.0). That's how I noticed it now. Please make this zoom feature optional as an option or parameter.

so the original code is, which maintains the view in size:
`var interval = Math.max(this.range.end - this.range.start, (end - start) * 1.1);`

**Comment by Vigneshjana** [comment]
Any Update on this feature.

**Comment by Maxouhell** [comment]
I also have this problem, and can't find any workaround.
Could you do something for this ?

Thanks for your help !
