### ISSUE TITLE
Bug with CSS-property "will-change: transform" in parental DIV

### ISSUE THREAD

**Issue by xbeowolf** [visjs/vis-timeline#201]
If timeline created inside of div with property "will-change: transform", sometimes it will be shown blank sheet on whole page. This bug occurs with items start date in future one month from the current date, and difference between time of those items not more then 1 minute. Also it cause anywhere on clusters with future time. There is a basic sample that shows this bug:
```html

<!DOCTYPE HTML>
<html>
<head>
  <title>Timeline | Future time bug</title>

  <style type="text/css">
    body, html {
      font-family: sans-serif;
    }
    .slideout-panel {
      will-change: transform
    }
  </style>

  <script src="./vis-timeline-graph2d.min.js"></script>
  <link href="./vis-timeline-graph2d.min.css" rel="stylesheet" type="text/css" />

</head>
<body>

<div class="slideout-panel">
  <p>
    Basic sample with bug on CSS property "will-change: transform" at any parental div. Comment line #12, and all will work again.
  </p>

  <div id="visualization"></div>
</div>

<script type="text/javascript">
  // DOM element where the Timeline will be attached
  var container = document.getElementById('visualization');

  // Create a DataSet (allows two way data-binding)
  var ts = [
    { id: 1, content: "item 1", start: "2019-12-20 16:57:55" }, // add month to current date
    { id: 2, content: "item 2", start: "2019-12-20 16:57:15" },
    { id: 3, content: "item 3", start: "2019-12-20 16:56:43" },
  ];
  var items = new vis.DataSet(ts);

  // Configuration for the Timeline
  var options = {
  };

  // Create a Timeline
  var timeline = new vis.Timeline(container, items, options);
  //timeline.fit();
</script>
</body>
</html>
```

**Comment by yotamberk** [comment]
Why are you using this property on the timeline wrapper?

**Comment by xbeowolf** [comment]
This property was used by https://github.com/Mango/slideout library at
"slideout-panel" class, it's wraps whole application, but a have workaround
this now by removing this property.

сб, 7 дек. 2019 г. в 23:34, Yotam Berkowitz <notifications@github.com>:

**Comment by xbeowolf** [comment]
It does not working in Chrome with last updates, and does not work in Opera. This effect with blank div on whole page arises for dates in future with short interval between them, thats can collapse to clusters, on some distance from current date. Add year for sample higher and it will be seen. Dates can come from server at any time, and bug arises on timeline with that CSS property without any control.

**Comment by yotamberk** [comment]
If you can supply a jsbin with the example with the issue, that would be great

**Comment by xbeowolf** [comment]
Look for output window here: https://jsbin.com/tehevihuja/edit?html,js,output
There is blank div instead timeline in Chrome and Opera. Open it in FF or in Edge and it will be seen expected result.

**Comment by yotamberk** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
It seems that using this property is not advised on too many elements.

> Don't apply will-change to too many elements. The browser already tries as hard as it can to optimize everything. Some of the stronger optimizations that are likely to be tied to will-change end up using a lot of a machine’s resources, and when overused like this can cause the page to slow down or consume a lot of resources.

Since the timeline is doing it's own optimization, there is no need in defining `will-change` on it. I advise you remove this property. 

I do not have a proper solution to make it work with this property set, but I do know it is not needed for the timeline to work efficiently.
