### ISSUE TITLE
Can nested groups contain duplicate subgroups?

### ISSUE THREAD

**Issue by tylersuchan** [visjs/vis-timeline#204]
I'm trying to make a timeline with nested groups. Essentially, I have my groups, which are all unique. The second "level" of groups are all the same, and the third "level" of groups *can* be different.
An easy way to think of this would be the following (I'll use restaurants as a topic):

Joe's Diner
 -> Lunch Menu
    -> Sandwich
    -> Soup
 -> Dinner Menu
    -> Spaghetti
    -> Chicken Parm
 -> Drink Menu
    -> Amaretto
    -> Bourbon 
    -> Rye

Amici's 
 -> Lunch Menu
    -> Sandwich
    -> Soup
    -> Mac & Cheese
 -> Dinner Menu
    -> Veal Parm
    -> Chicken Parm
    -> Rigatoni
 -> Drink Menu
    -> Amaretto
    -> Bourbon 
    -> Wine

I tried to get to that point, but it would seem that groups cannot have identical subgroups. I have an example codepen here that illustrates my issue:
https://codepen.io/tylersuc/pen/RwwOZoy

**Comment by yotamberk** [comment]
Why give the second groups the same ids? 
If you simply add the duplicate groups with different ids but belong to the other group, you will have the desired behavior.
```javascript 
 groups.add([{
            id: 1,
            content: "Joe's Diner",
            nestedGroups: [11, 12, 13]
        },
        {
            id: 2,
            content: "Amici's",
            nestedGroups: [14, 15, 16],
            showNested: false
        },

    ]);

    groups.add([{
            id: 11,
            content: "Lunch Menu",
        },
        {
            id: 12,
            content: "Dinner Menu",
        },
        {
            id: 13,
            content: "Drink Menu",
        },
                {
            id: 14,
            content: "Lunch Menu",
        },
        {
            id: 15,
            content: "Dinner Menu",
        },
        {
            id: 16,
            content: "Drink Menu",
        },
    ]);
```
