### ISSUE TITLE
Bug after #208 update

### ISSUE THREAD

**Issue by neoburgos** [visjs/vis-timeline#209]
After #208 update
and using //unpkg.com/vis-timeline@latest/dist/vis-timeline-graph2d.min.js

I got an error in: Item.js Line: 260.
Using W10P, Chrome Versión 78.0.3904.108 (Build oficial) (64 bits)

Example: https://numanos.com/test.php

Open Chrome console and click a box and you get the error.
Works fine if I use V.4.21.0 with https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.min.js

(Sorry if I have not explained myself well, I do not speak English or know how to use Github)

**Comment by Eerovil** [comment]
Got this issue as well, downgraded to 6.2.3 for a fix.

**Comment by yotamberk** [comment]
try the newest version
