### ISSUE TITLE
Horizontal scrollbar does not appear at the bottom of timeline

### ISSUE THREAD

**Issue by doan-sf** [visjs/vis-timeline#212]
I'm trying to make the horizontal scrollbar appear with the following setting options, but it does not work:

var options = {
    stack: true,
    horizontalScroll: true,
    zoomable: false,
    ....
}

Horizontal scrollbar can also not be shown in the example "Horizontal Scroll option".

Could anybody help me?

**Comment by chris-os** [comment]
horizontalScroll changes the behaviour when you scroll with your mouse. 
Instead of zooming, it will now change the Time-Axis, i.e. you move in time by scrolling with your mouse

**Comment by yotamberk** [comment]
This is not a bug. The horizontal scroll works as @chris-os mentioned.
It is a feature request from the past but will not be added. It's too complicated and not really demanded.
