### ISSUE TITLE
Infinite in loop redraw when browser zoom

### ISSUE THREAD

**Issue by tynvlad** [visjs/vis-timeline#213]
Base on https://github.com/visjs/vis-timeline/pull/174 .

I think bug was actual for in latest version of lib. I reproduced it in chrome 78.0.3904.108 using code from https://github.com/yotamberk/timeline-plus/issues/175 (https://jsbin.com/tidubabusu/1/edit?html,css,js,console,output).

**Comment by gricey432** [comment]
Is this fixed by #174 ?

**Comment by gricey432** [comment]
I can reproduce the same using `vis-timeline@6.2.4`

![visjs redraw](https://user-images.githubusercontent.com/1611345/70112402-e45b7980-16a0-11ea-934e-353f9172c20f.gif)
