### ISSUE TITLE
Keep date and time part of timeline visible for large datasets

### ISSUE THREAD

**Issue by Delamaine** [visjs/vis-timeline#215]
I am using timeline and display quite a large grouped dataset that requires scrolling to see all items. When scrolling through  (vertically in timeline component) and in the middle of the dataset neither the top date & time (see attachment) nor the bottom is visible. Is there any way to keep this in view or let it float to keep it in view?
![datetime](https://user-images.githubusercontent.com/3479514/70131722-aa619600-16e7-11ea-9bea-9fdd5b06577f.jpg)

**Comment by yotamberk** [comment]
Not exactly.
You can do one of the next:

1.  set the height of the timeline to a fixed height so the user can use the scroll bar of the timeline with `vertivalScroll` option + use this example (https://visjs.github.io/vis-timeline/examples/timeline/groups/visibleGroups.html) to scroll view to focus on items.
2. Use `position: fixed` or `position: sticky` on the top panel.
