### ISSUE TITLE
TimelineOptions missing cluster option on version  6.2.7

### ISSUE THREAD

**Issue by AsafEini** [visjs/vis-timeline#216]
@yotamberk , still not working for me.
seems that the TimelineOptions Interface does not contains "cluster" as it is written in the docs:

for vis-timeline version 6.2.7 :

export interface TimelineOptions {
align?: TimelineAlignType;
autoResize?: boolean;
clickToUse?: boolean;
configure?: TimelineOptionsConfigureType;
dataAttributes?: TimelineOptionsDataAttributesType;
editable?: TimelineOptionsEditableType;
end?: DateType;
format?: TimelineFormatOption;
groupEditable?: TimelineOptionsGroupEditableType;
groupOrder?: TimelineOptionsGroupOrderType;
groupOrderSwap?: TimelineOptionsGroupOrderSwapFunction;
groupTemplate?: TimelineOptionsTemplateFunction;
height?: HeightWidthType;
hiddenDates?: TimelineOptionsHiddenDatesType;
horizontalScroll?: boolean;
itemsAlwaysDraggable?: TimelineOptionsItemsAlwaysDraggableType;
locale?: string;
locales?: any; // TODO
moment?: MomentConstructor;
margin?: TimelineOptionsMarginType;
max?: DateType;
maxHeight?: HeightWidthType;
maxMinorChars?: number;
min?: DateType;
minHeight?: HeightWidthType;
moveable?: boolean;
multiselect?: boolean;
multiselectPerGroup?: boolean;
onAdd?: TimelineOptionsItemCallbackFunction;
onAddGroup?: TimelineOptionsGroupCallbackFunction;
onInitialDrawComplete?: (() => void);
onUpdate?: TimelineOptionsItemCallbackFunction;
onMove?: TimelineOptionsItemCallbackFunction;
onMoveGroup?: TimelineOptionsGroupCallbackFunction;
onMoving?: TimelineOptionsItemCallbackFunction;
onRemove?: TimelineOptionsItemCallbackFunction;
onRemoveGroup?: TimelineOptionsGroupCallbackFunction;
order?: TimelineOptionsComparisonFunction;
orientation?: TimelineOptionsOrientationType;
preferZoom?: boolean;
rollingMode?: TimelineRollingModeOption;
rtl?: boolean;
selectable?: boolean;
sequentialSelection?: boolean;
showCurrentTime?: boolean;
showMajorLabels?: boolean;
showMinorLabels?: boolean;
showTooltips?: boolean;
stack?: boolean;
stackSubgroups?: boolean;
snap?: TimelineOptionsSnapFunction;
start?: DateType;
template?: TimelineOptionsTemplateFunction;
visibleFrameTemplate?: TimelineOptionsTemplateFunction;
throttleRedraw?: number;
timeAxis?: TimelineTimeAxisOption;
type?: string;
tooltip?: TimelineTooltipOption;
tooltipOnItemUpdateTime?: boolean | { template(item: any): any };
verticalScroll?: boolean;
width?: HeightWidthType;
zoomable?: boolean;
zoomKey?: string;
zoomMax?: number;
zoomMin?: number;
}

did i missed anything?
if so i would be happy for assistance.
thanks!

**Comment by yotamberk** [comment]
Checkout https://visjs.github.io/vis-timeline/examples/timeline/other/clustering.html 
The example works. It might not be included in the `ts` file (which is another issue [I am NOT a fan of TS so I refuse to add anything to do with it...] - but it does work.) You are welcome to submit a PR with the addition of types in the options if you please.

**Comment by AsafEini** [comment]
Thanks it was little bit confusing.. by the way does vis-timeline supports
older versions of typescript? Below 3.1 for example?

**Comment by yotamberk** [comment]
> Thanks it was little bit confusing.. 

What is? There is documentation on how to use the `cluster` option here: https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options

> by the way does vis-timeline supports older versions of typescript? Below 3.1 for example?

No idea. As I said. Not a big fan of TS... TS support was submitted by the community and I reluctantly accepted it with a statement saying I will not maintain updates on it, and not force new features or options to provide TS support. So short answer: maybe, but you will have to check it yourself.
