### ISSUE TITLE
Having trouble with fixed width vertical axis labels

### ISSUE THREAD

**Issue by Thaliant** [visjs/vis-timeline#218]
I am trying to synchronize a vis.Timeline and vis.Graph2d on the same screen.  Scrolling and window synchronization is working great!  I am having trouble getting the y-axis labels on the Graph2d to be the same width as the group labels on the timeline.

Following a different example I found digging through the visjs issues, I was able to use this CSS to make the timeline's group labels a fixed width:

`.vis-timeline .vis-labelset .vis-inner { width: 100px; }`

Although the issue suggests it would work for graph2d, it does not.  The closest I have been able to get is with this CSS:

`#hm-timeline-graph .vis-panel.vis-left { width: 100px; }`

The results are pictured here:

![image](https://user-images.githubusercontent.com/3664216/70353589-5368d780-1833-11ea-9e56-fc89abe64d8e.png)

**The labels and the vertical line are in the correction position.**  It's the horizontal axis major and minor lines that are extending too far to the left.

I've tried applying width to several other DOM elements without success.  `.vis-left .vis-data-axis` doesn't seem to do anything.  `.vis-panel.vis-left .vis-y-axis` causes what appears to be _double_ the space allocated as pictured:

![image](https://user-images.githubusercontent.com/3664216/70353850-f7528300-1833-11ea-9861-74fb5228c706.png)

Is there a way to do it in CSS that I'm missing or is this an issue in the graph2d library?

Thank you in advance for the assistance!

Jeffrey

**Comment by yotamberk** [comment]
I will be able to help you much better if you can add a jsbin with your issue. It seems like it can be solved with CSS only, but for that, we need a starting point playground. Supply one and I will take a look at it.

**Comment by Thaliant** [comment]
Thank you so much for the prompt response!  

Here is a JSBin that illustrates what I'm trying to achieve - which is to have a graph and timeline synchronized with a fixed width for the vertical axis labels in both.

https://jsbin.com/fururih/edit?html,css,js,output

Your recommendation is appreciated!

Jeffrey

**Comment by yotamberk** [comment]
I've added this:
``` CSS
.vis-panel.vis-background.vis-horizontal .vis-grid.vis-minor {
    margin-left: 114px;
}
.vis-panel.vis-background.vis-horizontal .vis-grid.vis-major {
    margin-left: 116px;
}
```

Does this do the job?

**Comment by yotamberk** [comment]
Closing for now. Please reopen if this is still an issue.

**Comment by Thaliant** [comment]
Thank you for your assistance with this.  That worked!
