### ISSUE TITLE
handlebars item templates example is broken

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-timeline#22]
This example does not work anymore:
https://visjs.github.io/vis-timeline/examples/timeline/styling/itemTemplates.html

**Comment by mormotomyia** [comment]
Im thinking this and the dynamic content not working
(https://visjs.github.io/vis-timeline/examples/timeline/items/visibleFrameTemplateContent.html)
are related.

**Comment by mojoaxel** [comment]
> Im thinking this and the dynamic content not working (visibleFrameTemplateContent) are related.

No this is a different problem. The one you mentioned is already fixed in #23.
