### ISSUE TITLE
Custom styling of brackground grid (.vis-odd not applied properly)

### ISSUE THREAD

**Issue by knokit** [visjs/vis-timeline#228]
On the quarters scale, the `.vis-odd` class sometimes ends up applied to 3 consecutive dates - the labels also jump to the next month (ex: Mar -> Apr).

![background_styling](https://user-images.githubusercontent.com/3659829/71180251-11e41d80-2272-11ea-9747-4de7b8cf3c6d.gif)

I could not reproduce this using the [gridSyling example](https://visjs.github.io/vis-timeline/examples/timeline/styling/gridStyling.html) though.

**Comment by Async0x42** [comment]
I don't have a repo ready to reproduce, but I did run into something similar for `.vis-today` where at a certain zoom level, it would highlight today and the previous day as well.

**Comment by yotamberk** [comment]
Try it now please. I think I solved it here: #234.
Can you try with the newest version and update if it works or not?

**Comment by knokit** [comment]
@yotamberk, the latest version seems to work as expected. Thanks.
