### ISSUE TITLE
Check if navigator exists

### ISSUE THREAD

**Issue by timoleinio** [visjs/vis-timeline#231]
I've been using timeline component via vis.js library but since that is now EOL I thought it would be time to update to vis-timeline. However when I try to start my project locally with `npm start` I get the following error :

_ReferenceError: navigator is not defined
    at DOMutil (C:\pathtoproject\node_modules\vis-timeline\lib\DOMutil.js:226:17)_

It seems that getNavigatorLanguage in DOMutil.js file assumes that navigator object does exist. Since I'm starting a server with `npm start` navigator does not exist at that point.

Would it be possible to add a simple check to see if navigator exists or not and then return "en" if it doesn't exist at all? After that change my app and timeline started working again.

**Comment by timoleinio** [comment]
@yotamberk Unfortunately I'm still getting the same error after updating vis-timeline to the latest version. I think the check needs typeof:

`if (typeof navigator === 'undefined') {
    return "en"
}`

**Comment by yotamberk** [comment]
How is navigator defined when you get the error? What I did should have covered your case

**Comment by timoleinio** [comment]
I think the problem is that it's not defined at all. See https://stackoverflow.com/questions/2703102/typeof-undefined-vs-null/2703122#2703122

**Comment by velitchko** [comment]
Also getting this issue with the latest version. Is there any fix?
