### ISSUE TITLE
Infinite Loop Between Scroll and Redraw on Browser Zoom

### ISSUE THREAD

**Issue by arthur-cheung** [visjs/vis-timeline#238]
When adjusting browser zoom, it appears [`_redraw` is triggered which calls `_updateScrollTop`](https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L999) in `Core.js`. This in turn triggers event listeners on scroll which call [`onMouseScrollSide`](https://github.com/visjs/vis-timeline/blob/29f5f3b1d35ca6d8db93924efbc9349e86e840f8/lib/timeline/Core.js#L288-L297), which in turn calls [`_redraw`](https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L294) again, causing an infinite loop of scroll.

The symptoms are the timeline will slowly scroll to the top. When it reaches the top it then "jitters".

 ![infinite-scroll](https://user-images.githubusercontent.com/11646234/71696921-7ecaec00-2e0a-11ea-9139-9c232c4ec157.gif)

From what I can follow in the code, I would have expected this to happen all the time. But I can only reproduce it under certain browser zooms. In the case of the example I created in codesandbox, I can only produce it at 75% zoom. So I'm obviously missing some understanding here of how the code works.

Nevertheless, I think this can be fixed easily if a flag is just set to true when `_updateScrollTop` is called. Then in `onMouseScrollSide`, if this flag is true, set it to false and abort. I am happy to take this change on if this is deemed okay.

I would also like to fill in my gaps in understanding why this only occurs on certain zooms, if anyone knows.

[Example created in codesandbox here.](https://codesandbox.io/s/epic-banzai-s64zc)

EDIT - Additional notes:
- I have only observed this in Chrome.
- As the problem is with the scroll itself, it is important that `maxHeight` is set in the options to the timeline.

**Comment by yotamberk** [comment]
Very interesting. Not sure why this happens, especially only in Chrome.
