### ISSUE TITLE
Group overlap is not working anymore

### ISSUE THREAD

**Issue by justinbeatz** [visjs/vis-timeline#24]
Setting stack: false for groups is not working anymore, is stacking the items anyway:

Working example using vis 4.21.0:
https://jsfiddle.net/justinbeatz/2L0o8dn4/5
![image](https://user-images.githubusercontent.com/600565/62075274-ffc2fd80-b244-11e9-846e-eb70aae95b20.png)

Not working example using vis-timeline (master):
https://jsfiddle.net/justinbeatz/92emnv0a/3
![image](https://user-images.githubusercontent.com/600565/62075316-123d3700-b245-11e9-9ae6-be696633b35e.png)

**Comment by mojoaxel** [comment]
@justinbeatz Thanks for reporting this!

**Comment by justinbeatz** [comment]
I can confirm that this is fixed in the latest version 5.1.0

**Comment by yotamberk** [comment]
Awesome!
