### ISSUE TITLE
Has the bug about resizing timeline item been fixed?

### ISSUE THREAD

**Issue by ryamaguchi0220** [visjs/vis-timeline#241]
Hi,

I wonder if https://github.com/almende/vis/issues/2098 has been already fixed or not.

I can not reproduce it now, so I would say it has already been fixed.
However,  I'm not sure because the issue is still open and I can not find any PRs to fix it although @yotamberk was trying to fix it https://github.com/almende/vis/issues/2098#issuecomment-346947859

Thanks.

**Comment by yotamberk** [comment]
It has been fixed with one of `hammer.js` updates + one of my older PRs
