### ISSUE TITLE
timeline.setSelection() has the wrong zoom level

### ISSUE THREAD

**Issue by rsshilli** [visjs/vis-timeline#242]
**Vis-component**: Timeline
**Version**: 6.3.5
**OS & Browser**: Windows 10 & Chrome 79.0.3945.88

**Description**: I'm upgrading from vis.js 4.21.0 and the `timelines.setSelection()` method is super terrible now.  It used to scroll nicely to the item in the timeline but not change the zoom level. Now it zooms in to the millisecond (ms) level and the user has to zoom out manually to see anything.  It's very annoying.

**Minimal code example**: https://codepen.io/rsshilli/pen/bGNLpRz
Click on the "Select Item 1" or "Select Item 5" buttons to see what I'm talking about.  It should just scroll over to that item so it's in the middle but not modify zoom level like that.

**Comment by schallus** [comment]
Same problem for me since I updated to the latest version.

@rsshilli : Did you find a workaround meanwhile ?

Thanks

**Comment by rsshilli** [comment]
My workaround was to use the new vis.js for everything except for the timeline, where I'm still using 4.21.0 :-(.

**Comment by schallus** [comment]
> My workaround was to use the new vis.js for everything except for the timeline, where I'm still using 4.21.0 :-(.

Thanks for your answer.

I did come to a solution with the latest version and this might help you. I was calling the method `timeline.focus()` when selecting an item and it was also zooming. By reading the documentation, I found out that we could provide some options to the method in order to avoid zooming.

```javascript
this.timeline.focus(item, { zoom: false });
```

**Comment by rsshilli** [comment]
This whole issue seems to have gone away for me now in the latest vis-timeline v7.4.2. I'm closing this now.

**Comment by rsshilli** [comment]
OK. I'm wrong. The issue still exists, but only sometimes, which is strange. The workaround of passing the options `{focus: false}` into `setSelection` and then calling focus separately with the options `{zoom: true}` seems to work though. I'm going to leave this closed.
