### ISSUE TITLE
Multi-Select - deselect due to long press too short (configurable)

### ISSUE THREAD

**Issue by fras2560** [visjs/vis-timeline#244]
My company uses the timeline. To give background we have multi-select enabled. Some users are experiencing issues when attempting to drag the timeline. The users will select the item they would like to drag by clicking on the item and then proceed to drag. However, if you click and hold the item it will de-select. This is only an issue when multi-select is enabled (not present otherwise) The duration of the click and hold seems to be 251 ms (believe that it is the default from hammer.js). I think this default is probably fine for most use cases but it would be nice to be able to configure this. 

Once can test this by using the basicUsage.html and adding multi-select to it
 ```
 // Configuration for the Timeline
  var options = {
        multiselect: true,
        editable: {
          add: false,
          updateTime: true,
          updateGroup: false,
          remove: false,
          overrideItems: false,
        },
      };
```

I tried to look into this myself and adding a option for it but I am not exactly sure about how timeline and hammer interact. Any guidance or advice on this would be appreciated.

**Comment by fras2560** [comment]
Opened a PR (#245) for this issue with my attempt at allow for such a feature

**Comment by yotamberk** [comment]
Added with #245
