### ISSUE TITLE
Timeline bug: Items misplaced for 1 year after the 6.2.0 Release

### ISSUE THREAD

**Issue by Laur-lct** [visjs/vis-timeline#248]
Hi, 

It looks like the timeline Items misplaced for one year, at least in certain cases. I was able to identify the exact release which introduced this bug.

The below are the screenshots of the timeline with **the same** data.
The exact start and end date of each item (shipment) shown as item content text. 

Correct, expected behavior before the release [6.2.0](https://github.com/visjs/vis-timeline/compare/v6.1.1...v6.2.0):
![Screenshot 2020-01-14 at 11 23 51](https://user-images.githubusercontent.com/3942639/72336405-09400500-36c1-11ea-8d16-69e24eff06c9.png)

Incorrect positioning after the release [6.2.0](https://github.com/visjs/vis-timeline/compare/v6.1.1...v6.2.0) (2019-11-09)
![Screenshot 2020-01-14 at 11 29 32](https://user-images.githubusercontent.com/3942639/72336485-2d034b00-36c1-11ea-81d5-6ac50c9306cf.png)

**Comment by yotamberk** [comment]
Can you supply a jsbin to reproduce the issue? I can't do much without reproducing the problem.

**Comment by yotamberk** [comment]
This issue is not reproducible. If you supply a jsbin where I can reproduce the problem, I will reopen the issue.
