### ISSUE TITLE
'initialDrawDone' of undefined

### ISSUE THREAD

**Issue by kropamk** [visjs/vis-timeline#25]
Hi :)

thanks for plugin, good job!

I found in Graph2d.js file a redundant assignment in line 153. You try to set **me.itemSet.initialDrawDone = true;** but one line above You assigned the **'initialDrawDone'** property to **'me'** object. That **'itemSet'** object is not exist in script. Please check this and give me a feedback :)

**Comment by yotamberk** [comment]
Fixed with #41

**Comment by mojoaxel** [comment]
This was re-introduced by #5

**Comment by mojoaxel** [comment]
No, everything seams to work now. sorry!
