### ISSUE TITLE
IE broken since version 6.1.1

### ISSUE THREAD

**Issue by Goran-n** [visjs/vis-timeline#250]
Timeline is broken since version 6.1.1. The demos on the site are also broken, example 
![image](https://user-images.githubusercontent.com/10766074/72344840-82942380-36d2-11ea-93dc-1843852461ce.png)

Which uses this demo https://visjs.github.io/vis-timeline/examples/timeline/basicUsage.html

Tested on IE 11.

**Comment by yotamberk** [comment]
Closed with #251
