### ISSUE TITLE
Timeline does not work with Safari 

### ISSUE THREAD

**Issue by buelentucar** [visjs/vis-timeline#252]
In my project I use the timeline from vis.js. Version 4.21.0. The timeline works with the browsers Google Chrome and Firefox, but it does not load in Safari. What can I do? I ask for your help. 

<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.1/moment-with-locales.min.js"></script>
<script src="<?php echo sc_url_library('prj', 'Timeline', 'vis-4.21.0/dist/vis.js'); ?>"></script>
<link href="<?php echo sc_url_library('prj', 'Timeline', 'vis-4.21.0/dist/vis.css'); ?>" rel="stylesheet" type="text/css" />

**Comment by yotamberk** [comment]
We are now on v6.4.1.
Please try the newest version before submitting an issue on old versions.

**Comment by buelentucar** [comment]
On the site, only this version was the most current. Do you have a link. Thanks.

download, v4.21.0.zip
https://almende.github.io/vis/

**Comment by buelentucar** [comment]
> Wir sind jetzt auf v6.4.1.
> Bitte probieren Sie die neueste Version aus, bevor Sie ein Problem mit alten Versionen einreichen.

On the site, only this version was the most current. Do you have a link. Thanks.

download, v4.21.0.zip
https://almende.github.io/vis/

**Comment by yotamberk** [comment]
It's a deprecated version. this is the new version https://visjs.github.io/vis-timeline/

**Comment by buelentucar** [comment]
Thanks you :-)
