### ISSUE TITLE
IE11: Object doesn't support property or method 'remove' 

### ISSUE THREAD

**Issue by namiskuukkel** [visjs/vis-timeline#253]
This error is triggered from vis-timeline/lib/timeline/component/item/BoxItem.js function hide(), row 274. Function is triggered upon call to setSelection.

**Comment by yotamberk** [comment]
Please add a jsbin so I can reproduce the problem

**Comment by namiskuukkel** [comment]
Mmm sorry, I can't really use my work time to produce an example and I can't submit a part of my actual project. However, it's quite obvious that this is broken, because IE simply doesn't support calling .remove() on the DOM object itself. The breaking change was made in commit 9fc7c3d950dae1134e290929b829c5c660c37554. The previous way, element.parentNode.removeChild(element), was IE compliant.
