### ISSUE TITLE
Zoom does not work in Firefox

### ISSUE THREAD

**Issue by Janhouse** [visjs/vis-timeline#26]
I'm on latest Firefox 68.0.1 and zoom using scroll wheel doesn't seem to work in online examples. Zoom works in Chromium though.

**Comment by mojoaxel** [comment]
I can confirm this!

**Comment by javdome** [comment]
This bug was fixed in timeline-plus (see https://github.com/yotamberk/timeline-plus/issues/60).
So, should be fixed in following updates.
