### ISSUE TITLE
Wrong date axis label when scrolling out

### ISSUE THREAD

**Issue by gmhafiz** [visjs/vis-timeline#261]
With a simple markup, at a few zoom level, the date label range is not from 1-{{last_date_of_the_month}}

In the [jsbin link example](https://jsbin.com/linezuf/edit), The data range is from 2014-04-16 to 2014-04-19. When scrolling out, the date range seems to be 'spilled out' into the previous and next month:

[screenshot](https://imgur.com/5zRJbEu)

In this screenshot, the date range for the month of April is from 15 to 18.

This also happens in the provided [example](https://visjs.github.io/vis-timeline/examples/timeline/basicUsage.html)

Library: Vis timeline
Browser: Firefox 72.0.1, Chrome 79.0
OS: Linux

**Comment by yotamberk** [comment]
The issue you're encountering is due to jumping to the week number scale - not 'spilling out' of dates. It is a bug and needs to be fixed since it isn't a natural scale.
