### ISSUE TITLE
"WARNING: infinite loop in redraw?" when using flexbox

### ISSUE THREAD

**Issue by samvanemelen** [visjs/vis-timeline#268]
When using flexbox to center group names for the timeline, as recommended by [an old vis.js issue 3042](https://github.com/almende/vis/issues/3042), the console prints `"WARNING: infinite loop in redraw?"`. 

```
.vis-label {    
    display: flex;
    justify-content: center;
    align-items: center;
}
```

The table gets stuck in an infinite redraw loop and updates the table every second or so, regardless of zoom level. The issue only seems to occur when using Chrome as browser.

[jsbin example of the issue](https://jsbin.com/junamimequ/1/edit?html,css,js,console,output).

Might be similar to [issue 108](https://github.com/visjs/vis-timeline/issues/108)?

**Comment by gmcinalli** [comment]
@samvanemelen So without these rules the warning does not appear?

**Comment by samvanemelen** [comment]
> @samvanemelen So without these rules the warning does not appear?

Exactly, when commenting out that CSS part there is no issue. It's no major bug, but wanted to throw it out there anyway.

**Comment by yotamberk** [comment]
Seems to be working correctly now. 
Checkout your jsbin.
If you still feel there is an issue, give more details how to reproduce please.
