### ISSUE TITLE
Default test script doesn't work

### ISSUE THREAD

**Issue by ilancohen** [visjs/vis-timeline#30]
On a clean clone of the repo, running the default test script (`npm run test`) throws this error: 
```
C:\dev\vis-timeline\lib\timeline\component\css\dataaxis.css:2
.vis-panel.vis-background.vis-horizontal .vis-grid.vis-horizontal {
^

SyntaxError: Unexpected token .
```

We need to fix the importing of CSS files.

**Comment by mojoaxel** [comment]
@Thomaash Could you help out here? The css import breaks the test.

**Comment by Thomaash** [comment]
Try if it works with #37.

**Comment by yotamberk** [comment]
Thanks again @Thomaash !

**Comment by Thomaash** [comment]
You're welcome.
