### ISSUE TITLE
DataSet vs DataView

### ISSUE THREAD

**Issue by thomaspaulb** [visjs/vis-timeline#300]
Hi, I am using the visJS timeline component with nested grouping.

If I supply the groups as a plain array, I get a `DataSet` ([see here](https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Timeline.js#L342)), whereas if I supply my groups as a `DataSet`, I get a `DataView` ([4 lines below](https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Timeline.js#L346)) . Shouldn't the latter be:

`newDataSet = new DataView(new DataSet(groups.filter(filter)), {filter: filter});` ?

**Comment by yotamberk** [comment]
TBH I don't actually know... @Thomaash do you know the answer?

**Comment by Thomaash** [comment]
That wouldn't make any difference. If you supply an array then you have no reactivity. Even if you change something in the array or it's elements later, there's simply no way to know that it should be updated. The DataView would wait for changes from the DataSet that would never happen.

PS: I assume that Vis Timeline doesn't modify the group data, in other words that they can only be modified from the outside. If that's not the case, we may have a problem.

**Comment by yotamberk** [comment]
Thanks for the clarification!
