### ISSUE TITLE
Insert Items between 2 other items (with stack: false)

### ISSUE THREAD

**Issue by jweizman** [visjs/vis-timeline#307]
Hi

It would be nice to allow drag and drop of item(s) between 2 other items (with stack:false)
Currently when one wants to move Item 1 between 2 and 3:
![image](https://user-images.githubusercontent.com/2378511/74103918-585a4800-4b50-11ea-8c2d-84f8d1d5340c.png)

item 1 will just stay in place
![image](https://user-images.githubusercontent.com/2378511/74103930-6c9e4500-4b50-11ea-8dc7-94a910fa42e5.png)
where it would be nice to have an option to push the item 3 to the right :
![image](https://user-images.githubusercontent.com/2378511/74103936-8770b980-4b50-11ea-89ff-32bb7953ff77.png)

What do you think abou this idea?
thx

**Comment by razbensimon** [comment]
I am imagining it like we drag an app to already taken place on our smartphone screen.
cool behavior that can help for some items arrangement scenario.

**Comment by yotamberk** [comment]
You can implement this in your app with `setItem`. 
while dragging an item (using the `onUpdate`  even listeners`), you can check for intersecting items and simply shift the intersecting item forward or backwards with `setItems`. I don't see how and why we would want to implement this natively. What I suggested above should suffice.
