### ISSUE TITLE
Uncaught TypeError: vis.DataSet is not a constructor

### ISSUE THREAD

**Issue by kierandoyle** [visjs/vis-timeline#312]
vis-timeline/examples/timeline/basicUsage.html

Using:
<link rel="stylesheet" type="text/css" href="https://unpkg.com/vis-timeline@7.1.0/styles/vis-timeline-graph2d.min.css">
<script src="https://unpkg.com/vis-timeline@7.1.0/peer/umd/vis-timeline-graph2d.min.js"></script>

**Comment by javdome** [comment]
I think that in thst example you must use the standalone version:
https://unpkg.com/vis-timeline@7.1.0/standalone/umd/vis-timeline-graph2d.min.js

The peer version does not load the moment library and vis-data library.

**Comment by kierandoyle** [comment]
Thank you - that resolved it

**Comment by shariquekhan1997** [comment]
I have vis-network as well as vis-data but still this issue is coming. Previously it was working but when I transfer this code to my different machine and ran npm install I am getting this issue. In new machine both packages are present.
