### ISSUE TITLE
How can I load the data dynamiclly without setInterval?

### ISSUE THREAD

**Issue by InbarTakdim** [visjs/vis-timeline#314]
I need every 1min to make an API call and then render the timeline. There is something built-in I can use? cause if I use set interval it's scrolling the page and change all the collapsed subgroups to be expanded (I would like to stay the collapse and expand of subgroups in their old status).

**Comment by javdome** [comment]
How are you doing it right now?... are you generating the whole timeline each time?

**Comment by yotamberk** [comment]
You can save the state of the collapsed and un-collapsed groups and every time you fetch data from your API, make sure the imported data is set with the previous state saved before the data was received. That way the timeline will not jump.
