### ISSUE TITLE
exports after breaking changes logs warning

### ISSUE THREAD

**Issue by AsafEini** [visjs/vis-timeline#322]
Hey,
thanks for maintaining vis-timeline, very good stuff :).

im using the standalone build as im importing from vis-timeline/standalone.
i have noticed that i get the following warning :

This build has been deprecated.

In case you are importing this through a URL it will result in a 404 eventually.
In case you are importing this through Node it will be replaced by the peer build eventually.

am i doing something wrong?

**Comment by yotamberk** [comment]
@Thomaash Do you care to explain the rationale?

**Comment by Thomaash** [comment]
Hi @AsafEini,

the standalone shouldn't produce this warning. Searching through the built files the error's just not there and I don't receive the warning in my tests either. Could you provide some more info, please? Ideally an MWE like a project where it happens?

Thanks.

PS: Also note that you get the error by importing it, not by using it. If you have some forgotten import like `import vis from "vis-timeline";` or a script tag in some page pointing to the dist directory you'll get this warning even if you use Timeline from `vis-timeline/standalone`.

**Comment by rovio-daniel-jackson** [comment]
Running into this with an Angular TypeScript project, currently: 
```
import { Timeline, TimelineOptions } from 'vis-timeline';
```
triggers the above warning, but then when I append `/standalone` to the import it causes module resolution to fail, with:

```
error TS7016: Could not find a declaration file for module 'vis-timeline/standalone'. '/Users/cloakedninjas/app/node_modules/vis-timeline/standalone/index.js' implicitly has an 'any' type.
[ng]       Try `npm install @types/vis-timeline` if it exists or add a new declaration (.d.ts) file containing `declare module 'vis-timeline/standalone';`
[ng]  import { Timeline, TimelineOptions } from 'vis-timeline/standalone';
```

Any tips?

**Comment by Thomaash** [comment]
Just ignore it and stick with the deprecated bundle for now.

I have a fix locally but it has to be deployed in stages as it relies on the ESNext builds from the other packages (that are not updated yet):

### 1st
- [ ] ~Update Vis UUID to use the common configuration.~
- [x] Get rid of Vis UUID.

### 2nd
- [ ] Update Vis Util to use the common configuration.

### 3rd
- [ ] Update Vis Data to use the common configuration.

### 4th
- [ ] Update Vis Graph3D to use the common configuration.
- [ ] Update Vis Network to use the common configuration.
- [ ] Update Vis Timeline to use the common configuration.

### 5th
- [ ] Update Vis Charts to use the common configuration.

**Comment by yotamberk** [comment]
Can this issue be closed?

**Comment by AsafEini** [comment]
yes

‫בתאריך שבת, 14 במרץ 2020 ב-18:32 מאת ‪Yotam Berkowitz‬‏ <‪
notifications@github.com‬‏>:‬
