### ISSUE TITLE
setItems performance issue

### ISSUE THREAD

**Issue by Fiorello** [visjs/vis-timeline#342]
Hi, thanks for this project, it is truly exceptional.
I have a performance problem with my implementation.
In my timeline i have thousand of items divided in two groups.
When i have to add items to the timeline i use **setItems** function and it takes about 3 seconds for 1000 items.
Debugging vis-timeline code, i have not found an obvious bottleneck, but i measured how long it took to add a single element in the **_addItem** function.
It took about  3 ms per item, so 3ms * 1000 items = 3000ms.
What I don't understand is the difference with your [performance example](https://visjs.github.io/vis-timeline/examples/timeline/other/performance.html).
In that example there are many more elements, but the render is immediate.

Has anyone faced similar problems?
Thanks for your time

**Comment by yotamberk** [comment]
I will need to see your implementation to see the problem. Can you reproduce it in a simple jsbin?

**Comment by Fiorello** [comment]
After some tests, I realized that the problem was rendering too many elements on the DOM, so the only solution I found is the clustering of the elements.
I don't think there is another solution, so I close the bug.
