### ISSUE TITLE
Items in subgroups incorrectly stacking on initial draw and after setItems

### ISSUE THREAD

**Issue by mpilone** [visjs/vis-timeline#343]
I'm seeing an issue in 7.1.3 with items stacking when they shouldn't. The issue appears on the initial draw of the timeline as well as after calling set items. I attached a test case which is just a modified version of a bundled example.

Steps to reproduce:

1. Drop the example over the existing one in examples/timeline/items/
2. Load the example, in my case with Firefox 73.0.1 on macOS 10.14.6
3. See the stacked items such as BBC (see screenshot)
4. Drag the timeline and notice that the BBC items stack properly, all in one line.
5. Click the "setItems" button and noticed that the BBC items stack again.

Expected behavior is that the items/subgroups that abut but don't overlap should be in a continuous row.

I _think_ this is related to subgroups because I don't see it in other places where I don't use subgroups in the timeline but I'm not 100% sure of that.

This might be related to #103 and/or #74 but it isn't clear.

<img width="1559" alt="Initial draw stacking" src="https://user-images.githubusercontent.com/3026098/75476326-65f13980-5968-11ea-8f6c-bfe1c160a273.png">

<img width="1559" alt="After move correct" src="https://user-images.githubusercontent.com/3026098/75476386-7c979080-5968-11ea-868a-a44b6420032c.png">

[expectedVsActualTimesItems.html.zip](https://github.com/visjs/vis-timeline/files/4263461/expectedVsActualTimesItems.html.zip)

**Comment by mpilone** [comment]
I tracked the problem down to the Stack.collisionByTimes method. It looks like that method does a "less than or equal" comparison so abutting subgroups will be stacked. This is different from the behavior of Stack.collision used for items that only does a "less than" comparison so abutting items remain in the same row.

I modified collisionByTimes to read:
```
/**
 * Test if the two provided objects collide
 * The objects must have parameters start, end, top, and height.
 * @param {Object} a          The first Object
 * @param {Object} b          The second Object
 * @return {boolean}        true if a and b collide, else false
 */
export function collisionByTimes(a, b) {

  const timeOverlap = a.start < b.end && a.end > b.start;
  const heightOverlap = a.top < (b.top + b.height) && (a.top + a.height) > b.top;
  return timeOverlap && heightOverlap;

  // return (a.start <= b.start && a.end >= b.start && a.top < (b.top + b.height) && (a.top + a.height) > b.top ) ||
  // (b.start <= a.start && b.end >= a.start && b.top < (a.top + a.height) && (b.top + b.height) > a.top );
}
```
And it resolved my issue. It looks like this method is only used to layout subgroup heights so it seems pretty safe to modify. I attached an updated, slightly simplified test case that shows the issue when the existing logic is used and shows the proper behavior when the modified logic is used.

I don't know this code too well so I'd appreciate a second set of eyes on the change. I can submit a pull ticket if it makes sense.

I also don't understand why the item top is calculated using half the vertical margin in code such as:
```
items[i].top = subgroups[items[i].data.subgroup].top + 0.5 * margin.item.vertical;
```
If you mix normal items and subgroups in the same group the heights don't align properly. But that is another ticket for another day.

[expectedVsActualTimesItems.html.zip](https://github.com/visjs/vis-timeline/files/4289682/expectedVsActualTimesItems.html.zip)

**Comment by yotamberk** [comment]
Hi @mpilone , PRs are always welcome! Submit one and I will look over it.
It seems that you hit the nail on the head. It should solve the issue as you expect and see.

> I also don't understand why the item top is calculated using half the vertical margin in code such as...

I'm honestly not sure... I think the margin was thought of as a margin from top and bottom. So maybe that's why it's half? really not sure... It seems to be wrong to me.
