### ISSUE TITLE
import vis-timeline without vis-data

### ISSUE THREAD

**Issue by razbensimon** [visjs/vis-timeline#346]
Hi
I am trying to import the `esnext` build  by:

`import 'vis-timeline/esnext';`

but get compile error (with `create-react-app` + Typescript)
```
Failed to compile.

./node_modules/vis-timeline/esnext/esm/vis-timeline-graph2d.js
Module not found: Can't resolve 'vis-data' in '/Users/raz/bringg/bringg-web/react-app/node_modules/vis-timeline/esnext/esm'

```

It actually wants me to install by myself the `vis-data` library.
 but I don't use it and from the docs, I should not install it (only in `peer build)

**Comment by yotamberk** [comment]
True. Will be fixed soon.

**Comment by yotamberk** [comment]
https://github.com/visjs/vis-timeline/blob/master/README.md#esnext-build it says:
> This is the same as the peer build but without any bundled dependencies or pollyfills

meaning you will need to add vis-data as a peer. The docs were correct after all.
please include vis-data if you are intending to use `esnext` build.

**Comment by Thomaash** [comment]
The reason why it is in peer deps is that you have to have one and only one version of it in your project. At the moment you have two or more it will start misbehaving. For example if Vis Timeline had Vis Data as it's dep and Vis Network had a different version of Vis Data as it's dep it wouldn't be possible to use the same data set in both. And who knows what would be imported through `import { DataSet } from "vis-data";` that could even be a third version not working anywhere.

I know it would be more convenient and probably less confusing for some people but it would break projects of some others.

**Comment by razbensimon** [comment]
ok. I understanding the reasons for `vis-data`.
but now my build breaks for other new packages.

![image](https://user-images.githubusercontent.com/5955905/77065125-6326b900-69e9-11ea-8d70-5a34a8807515.png)

moment and vis-data are very understandable, but why I need to add those new packages too to my `package.json`?

It will cause confused developers, looking in theirs `package.json` and wondering if they can remove packages that 'no one' import theirs the project.

also, this new package list is exaggerated for my taste ...

wdyt?

**Comment by Thomaash** [comment]
We had it the other way, people complained. We have it this way, people complain. From my perspective this is inconvenient for many but the alternatives would make certain things impossible for some. In other words I'd stick with this.

Another solution would be to publish yet another set of packages probably under the @visjs namespace. Something like `@visjs/timeline` (a few deps, great for <script/>), `@visjs/timeline-standalone` (no deps, great for JSFiddle), `@visjs/timeline-esnext` (many deps, great for bundlers). Although now I think this is the way we should have done it (Wouldn't be great to have the advantage of hindsight before you do something?) I do not have the time to do this plus it would add to the confusion that already exists here plus obviously even more breaking changes if we wanted to abandon the others.

**Comment by RonRofe** [comment]
Have the same issue. Any solution published?
