### ISSUE TITLE
Setting title of custom timebars via function has no arguments

### ISSUE THREAD

**Issue by smee** [visjs/vis-timeline#351]
The call to the function uses the date as `this`, not as the function argument. The callback will get an `undefined` argument but `this` will be bound to a Date object.

See https://github.com/visjs/vis-timeline/blob/d535f69ab067fa55f06c2f2f8f95ef9019db5bb2/lib/timeline/component/CustomTime.js#L164
should imho be
``` javascript
title = title.call(this,this.customTime);
```

**Comment by yotamberk** [comment]
I believe you are correct! Can you submit a PR for this fix?
