### ISSUE TITLE
adopt pull-requests fom vis and timeline-plus

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-timeline#36]
While @yotamberk is working on #5 i thought I could start adopting pull-requests from vis one by one:

...
https://github.com/yotamberk/timeline-plus/pull/37
https://github.com/yotamberk/timeline-plus/pull/36
https://github.com/yotamberk/timeline-plus/pull/16
https://github.com/yotamberk/timeline-plus/pull/15
https://github.com/yotamberk/timeline-plus/pull/12
https://github.com/yotamberk/timeline-plus/pull/3
https://github.com/yotamberk/timeline-plus/pull/1

- [ ] https://github.com/almende/vis/pull/4286
- [ ] https://github.com/almende/vis/pull/4285
- [ ] https://github.com/almende/vis/pull/4274
- [ ] https://github.com/almende/vis/pull/4231
- [ ] https://github.com/almende/vis/pull/4166
- [ ] https://github.com/almende/vis/pull/4153
- [ ] https://github.com/almende/vis/pull/4143
- [ ] https://github.com/almende/vis/pull/4117
- [ ] https://github.com/almende/vis/pull/4115
- [ ] https://github.com/almende/vis/pull/4110
- [ ] https://github.com/almende/vis/pull/4098
- [ ] https://github.com/almende/vis/pull/4091
- [ ] https://github.com/almende/vis/pull/4038
- [ ] https://github.com/almende/vis/pull/3940
- [ ] https://github.com/almende/vis/pull/3814
- [ ] https://github.com/almende/vis/pull/2617

**Comment by yotamberk** [comment]
#5 is ready to go. I think there is no need for this anymore

**Comment by mojoaxel** [comment]
As far as I see it we now can go two directions now:

#### Just merge #5 and hope that everything works and things generally improve.

- :+1:  It is the fastest way for improving the library and release a new version.
- :+1: All changes have been testes in timeline-plus by @yotamberk and others.
- :grey_exclamation: Needs a Major version increase because we can not be sure what actually has changed. A detailed update of HISTORY and release notes would be not possible.
- :grey_exclamation: The git history of the unique PR is not visible in the new branch. Everything would be something like "merged timline-plus features (#5)".
- :grey_exclamation: There is no attribution to the original contributors of these improvements and fixes. All these dozens of PRs and changes would be attributed to @yotamberk.

#### We merge all vis and timeline-plus pull requests one by one

The idea is to merge (cherry-pick) every PR from vis and timeline-plus one by one. While merging we could have a look at the [merge-timeline-plus branch] to see how things should look in the end.

- :+1: We can test and release every PR and make sure everything works fine after each merge.
- :+1: We would have a nice git history and could "blame" every change to a specific PR. This allows us to create a detailed release HISTORY.
- :+1: We could have attribution to the original contributors of each PR.
- :grey_exclamation: A lot of work, that would propably need a few weeks to complete (60+ PRs, each 10-20 minutes).
- :grey_exclamation: Some PRs would be hard to merge and would require a lot of looking into the [merge-timeline-plus branch].

_Hey everybody! What do you think?_

**Comment by mojoaxel** [comment]
I personally like the idea more to merge every PR seperatly and test and release often. We did the same thing in vis-network and it worked out fine. We would very much rely on the [merge-timeline-plus branch] that @yotamberk created to see how things should look in the end. This work was NOT in vane!
The main reasons I prefer this method is the attribution and the git-history. Also I would feel more stable to release one feature by one.

I also could live with just merging #5 and make a v6 release. This would basically mean a break with the old git-history and an new start. It depends if you folks want to see this library progress more fast or more stable! I don't want to decide this!

**Comment by jczacharia** [comment]
I agree with @mojoaxel that merging in increments will be more stable but I also think that if major features are missing in `vis-timeline` that are only available in `timeline-plus` then developers will be more inclined to just stick with using `timeline-plus`.

Also, I ran a smoke-test of `vis-timeline` with the `merge-timeline-plus` and I am getting the exporting errors e.g. `export 'Timeline' was not found in 'vis-timeline'`.

I haven't been able to test @yotamberk merges but b/c of exporting issues but I see that this repo does not include Typescript typings `index.d.ts` which was very helpful to me in `timeline-plus`.

**Comment by bladerunner41** [comment]
As a user I'd be happy with a major v6 release that merged `timeline-plus` without full history.

As a maintainer even if you do 5-6 cherry picked PR's an hour when there's 60+ that still a lot of time to ask that could be spent elsewhere.  The layers of sediment for viewing would still exist in an archived repo when needed.

**Comment by yotamberk** [comment]
Hey guys,
Although in theory the second option is a safer and has a better tracking of the history etc. It is A-LOT of work that I simply don't want to do... I've done a lot of work for timeline-plus and to resubmit all the changes done there one by one will be a pain-staking job that is simply not on my agenda or priority list. This will take me many weeks to finish. 
Maybe if I get paid for my time working on it I might consider doing it, if it's really that important for/to the community, but it will still require a few weeks of work.

I know it's not ideal, but I recommend the first option. It will allow me and the community to pursue the work on this module without opting out to use timeline-plus. 
Once we accept this PR, I will declare deprecation to timeline-plus and dedicate all my time on this module. We have still lots of work to get this module where it should be. I don't want to waste more time...

**Comment by mojoaxel** [comment]
@yotamberk I'm going you fully support your decision as the main maintainer of this library!
Lets try to merge #5 in the near future and progress from there! :+1
