### ISSUE TITLE
Standalone build injects inline styles in head

### ISSUE THREAD

**Issue by Liombe** [visjs/vis-timeline#376]
Since vis-timeline@7.3.0, the standalone build injects inline styles in head after any of my project stylesheets, which breaks my custom style. Is it an intended feature ?

**Comment by yotamberk** [comment]
This can be solved by wrapping the timeline with your own class and add to your custom styling another wrapper with that class. 
Does this solve the problem?

**Comment by Liombe** [comment]
Yes it is a solution to my broken custom css. Thank you. But my question hasn't been answered. If it's an intended feature, why in examples it's required to embed the vis-timeline stylesheet ?

**Comment by yotamberk** [comment]
Glad to hear. The stylesheet is required for the timeline to work. It is an intended feature.

**Comment by abeverley** [comment]
Just a comment to say that if for legacy reasons you want to keep your custom styles in a custom stylesheet, then you can do that by being more specific with the selectors.

For example, if you want to override ```.vis-item .vis-item-overflow``` then you can use ```.vis-timeline .vis-item .vis-item-overflow``` instead, which will then take precedence over the inline style.
