### ISSUE TITLE
Zoomable false is ignored in 5.0.0

### ISSUE THREAD

**Issue by ydg2018** [visjs/vis-timeline#39]
In my angular component i have working timeline with the old vis@4.21.0 library with the options below which works as expected, but when i change to the vis-timeline 5.0.0 library it totaly ignores those settings and always zooms instead of scrolls when using the mouse wheel.
`const options = {
        width: '100%',
        zoomable: false,
        zoomKey: 'ctrlKey',
        horizontalScroll: true
      };`

Is this a bug in the new library or am i missing something the disable zoom and enable horizontal scroll?

**Comment by mojoaxel** [comment]
dublicate of #14

@ydg2018 Should be fixed in [v5.1.0](https://github.com/visjs/vis-timeline/releases/tag/v5.1.0). 
Can you please confirm!

**Comment by ydg2018** [comment]
I confirm that the zoomable false and horizontalscroll true works in 5.1.0
Thanks for the new version.
