### ISSUE TITLE
Additional columns?

### ISSUE THREAD

**Issue by plutocow** [visjs/vis-timeline#396]
Hello, I'm looking at the documentation and examples... 
I was wondering if it is possible to have additional columns?
ie.

[  Name  ] [  Location  ] | [ Time ]
[  A        ] [  America   ]
[  B        ] [  Germany  ]

**Comment by yotamberk** [comment]
What do you mean?

**Comment by plutocow** [comment]
Sorry for bad example but something like this:

![image](https://user-images.githubusercontent.com/47922440/77911243-36717c00-72dc-11ea-8c48-2248a1af1b34.png)

This is the group example but I added an extra column.

**Comment by yotamberk** [comment]
you can use `groupTemplate` option to generate whatever you want in the column.

manipulating the css and the groupTemplate you can get the desired behavior.
