### ISSUE TITLE
Examples using external scripts fail to load in Firefox

### ISSUE THREAD

**Issue by richardeaxon** [visjs/vis-timeline#4]
Githup is all https causing mixed content from CDN's to fail loading with the below message. All CDN URL's used in examples should be changed to https.

Blocked loading mixed active content “http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js”

**Comment by mojoaxel** [comment]
@richardeaxon Thanks! Could you provide a pull request? That would be wonderful.

**Comment by richardeaxon** [comment]
Pull request #7 created.

**Comment by mojoaxel** [comment]
fixed by @richardeaxon with #7
