### ISSUE TITLE
Start at "topmost" group/move to group name

### ISSUE THREAD

**Issue by molkemon** [visjs/vis-timeline#40]
Hello,

I am using timeline with a significant amount of groups (Names sorted by Alphabet) that cannot be displayed on the screen at once. By default, when timeline is created, it starts out the very bottom (so Names starting with Z are in view). Is there a way to change this behaviour so timeline starts at the top instead? 

Both groups and items are populated via ajax.

Item focus is not really a solution, since the first item does not necesseraly belong to the first Group (and in fact since I don't need them at the moment, my items don't have id's at all currently, allthough I could add some if that somehow helps).

Also, related, is there a way to make timeline jump to a group by name? So I can have like a search field and once executed, the view centers on that group?

**Comment by jczacharia** [comment]
In the timeline options did you set `orientation: 'top'`?
https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options

**Comment by yotamberk** [comment]
It seems like you're asking 2 questions:

1. >  Is there a way to change this behaviour so timeline starts at the top instead?

The answer: Yes. Se what @jczacharia responded.

2.   >  Is there a way to make timeline jump to a group by name? So I can have like a search field and once executed, the view centers on that group?

Yes. Checkout `timeline.focus` method - https://visjs.github.io/vis-timeline/docs/timeline/#Methods.
I'm quite sure using it you can achive this. If not, you can also try using pure js to find the group element from the DOM that contains your search input and scroll to it.
