### ISSUE TITLE
Request: Remove all sourceMappingURL's from Standalone build

### ISSUE THREAD

**Issue by melloware** [visjs/vis-timeline#410]
The Standalone MIN build goes from 555K down to 483K just by removing the sourceMappingURL's from the JS and CSS.

I don't think these should be part of the Standalone MIN build.

**Comment by yotamberk** [comment]
Can you submit a PR with this change?

**Comment by yotamberk** [comment]
This should be applied in `vis-dev-utils` here: https://github.com/visjs/vis-dev-utils/blob/master/src/module/generate-rollup-configuration/index.ts

**Comment by yotamberk** [comment]
(basically, any time the `*.min.*` file is generated, add `sourceMap: false` to the output bundle generated)

**Comment by melloware** [comment]
This is fixed with: https://github.com/visjs/vis-timeline/pull/483
