### ISSUE TITLE
groups._data does not contain data anymore.

### ISSUE THREAD

**Issue by Kaliph** [visjs/vis-timeline#414]
Hello,

in earlier versions of vis.js it was possible to retrieve the data of a group by using 
groups._data[id].value. The same applies for items. items._data[id].value also does not work anymore. The groups._data object seems to be empty. Is there a different way now to retrieve the groups and items data by id?

Thanks for helping.

**Comment by Thomaash** [comment]
Underscore tells you that it's private and can break your project without prior notice (exactly what happened). Instead of `groups._data[id].value` use `groups.get(id)?.value` (no underscores so it's safe to use) or create an issue in Vis Data if that doesn't suit your needs.
