### ISSUE TITLE
[Timeline] Vertical auto scroll on item dag

### ISSUE THREAD

**Issue by adamkisorsi** [visjs/vis-timeline#417]
*Is there any way to make the vis.js timeline scroll vertically when dragging an item? 

With a fixed height and a lot of groups out of view, if one needs to move an item to a different group, he needs to drag it down a couple of groups, let go, scroll or drag the timeline manually a bit, to then re-grab the item and continue dragging. 

I would like to just drag the item and have the timeline scroll automatically while I do that. I haven't found any combination of options to get there. Does anyone have some suggestions please? Thanks a lot.

**Comment by yotamberk** [comment]
you can listen to the item move event and check if the item's time is need the timeline end\start and set the options of the timeline to a new value of start and end (shifted by the amount of time you wish to move).
