### ISSUE TITLE
introduce semantic versioning

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-timeline#42]
see https://github.com/visjs/vis-network/issues/1

**Comment by mojoaxel** [comment]
see also #61 

@Thomaash I think we should introduce auto release (like in vis-network) here, too!
@yotamberk What do you think about an automated release process? It works fine for the other modules but I would consider you the maintainer of this library...

**Comment by Thomaash** [comment]
I also think we should have it here too, that's why I created #57. Just merge it, give me access to this repo and I'll take care of the rest.
