### ISSUE TITLE
Upgrade from v4.21.1 to 6.x or higher

### ISSUE THREAD

**Issue by christophepersoz** [visjs/vis-timeline#448]
Hello,

I'm working with an old version, 4.2.1 which only suffer of one bug on height redraw on my app. 

I maybe plan to upgrade to 6.x or higher version to see if new version fix this, but is there a place that explain what are the major changes? Mostly to simplify the upgrade process.
Or do I need an ant work to find all the differences to adapt my old dev to this new library version?

Thanks a lot for your work!

**Comment by yotamberk** [comment]
you can find all that has been updated here: https://github.com/visjs/vis-timeline/releases
