### ISSUE TITLE
editable.remove = false is not working

### ISSUE THREAD

**Issue by Kaliph** [visjs/vis-timeline#451]
Hello, today I recognized that the editable option remove is not working correctly. If setting remove to false, the delete Button still appears.

I think it has to do with this line of code.

`var editable = (this.options.editable.overrideItems || this.editable == null) && this.options.editable.remove || !this.options.editable.overrideItems && this.editable != null && this.editable.remove;`

Thankyou

**Comment by adamlarat** [comment]
Hi ! I have the same issue in our app. The delete Button still appears when the event is selected but becomes suddently not editable anymore. 
As pointed out by @Kaliph, this happens in the `_repaintDeleteButton` function. 
However, the error is not in the declaration of the `editable` variable but rather in the section allowing to destroy an existing button. 
Indeed, the condition was `else if (!this.selected && this.dom.deleteButton) {` which destroys the button only when the event is unselected. 
Instead, the condition should be `else if ( (!this.selected || !editable) && this.dom.deleteButton) {`. 
This fixes the issue by me. 
Cheers !
