### ISSUE TITLE
Performance: Snaping

### ISSUE THREAD

**Issue by hypery2k** [visjs/vis-timeline#453]
For performance optimization would be great if the [snap](https://github.com/visjs/vis-timeline/blob/master/lib/timeline/optionsTimeline.js#L160) function would be just called on certain events, e.g. on click
It could be one additional parameter, so it would be backward-compatible.
Any thoughts on this? maybe @mojoaxel ?

**Comment by luchsamapparat** [comment]
In our concrete scenario we have a function `getClosestQuarterOfMonth` that does some more or less expensive calculation:

```ts
export function getClosestQuarterOfMonth(date: Date) {
    // Quarters per month
    const daysInCurrentMonth = getDaysInMonth(date);
    const averageQuarterDaysInMonth = daysInCurrentMonth / 4;
    const startOfMon = startOfMonth(date);
    const quarters = times(5, (index) => addDays(startOfMon, index * averageQuarterDaysInMonth));
    return closestTo(date, quarters);
}
```

This function is configured as the `snap` function in the timeline options.

![image](https://user-images.githubusercontent.com/875017/80496604-b6394780-8969-11ea-9bf8-c162126c60e8.png)

As the screenshot shows, it is called by `getEventProperties` every time the onmouseover event fires, which is quite often :-)

In our case, the `snap` function is only relevant when dragging timeline items. We do not even listen to the mouseover event. So it would be nice to be able to prevent having that function called every time the user moves his/her cursor over the timeline

**Comment by hypery2k** [comment]
@mojoaxel Any thoughts on that?

**Comment by mojoaxel** [comment]
I haven't had a look at the code for quite some time. I guess @yotamberk is the real expert.

**Comment by yotamberk** [comment]
Seems like a legit request. It would be great if you could submit a PR with this change. I will go over it and add it if it seems to do the job.

**Comment by luchsamapparat** [comment]
@yotamberk  Would this solution be alright for you?

https://github.com/luchsamapparat/vis-timeline/commit/e5e17973d4abe6ae635cde277683d46f878ee8bb

It's untested as I have trouble building `vis-timeline` locally and don't have the time to investigate right now.

```
> mocha --exit --require vis-dev-utils/babel-register


TypeError: $ is not a function
    at Object.<anonymous> (C:\Users\Marvin\Projekte\vis-timeline\node_modules\core-js-pure\modules\/es.array.is-array.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module._compile (C:\Users\Marvin\Projekte\vis-timeline\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.newLoader [as .js] (C:\Users\Marvin\Projekte\vis-timeline\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

**Comment by hypery2k** [comment]
just build your fork and works for me, created a PR for this:
