### ISSUE TITLE
Deeply nested subgroups can cause subgroups to become displaced, appearing at the top of the timeline

### ISSUE THREAD

**Issue by zack-baker** [visjs/vis-timeline#459]
I'm currently working on a project using vis-timeline, and encountered a bug resulting from having a deeply nested subgroup hierarchy. If a timeline has 3 or more levels of nested subgroups, it's possible to expand and collapse them in a particular way which results in some groups appearing at the top of the scheduler, unnested. Re-expanding every group will fix this, rearranging every group into it's proper position.  Further investigation found that the bugged groups had a null group id, as opposed to their proper assigned IDs. 

Reproduction instructions and an example are available here:
[jsFiddle example](https://jsfiddle.net/zack_baker/24zduywg/15/)

Specs are:

OS: Manjaro 5.4.35
Browser: Firefox Developer Edition 76.0b8, Chromium Version 81.0.4044.122

Let me know if I can be of any assistance.

Thanks in advance!

**Comment by rg2609** [comment]
any update on this @zack-baker @yotamberk

**Comment by yotamberk** [comment]
No workaround I can think of except calling the timeline to redraw itself. Maybe that will work.
This is a bug that needs to be fixed but I am not available to do this myself.

**Comment by ktayal-tech** [comment]
@yotamberk @rg2609 
PR raised for an issue which seems similar to this, https://github.com/visjs/vis-timeline/issues/1109.

**Comment by ktayal-tech** [comment]
Please review https://github.com/visjs/vis-timeline/pull/1494 @mojoaxel @yotamberk

**Comment by mojoaxel** [comment]
Fixed with #1494 by @ktayal-tech 🎉
