### ISSUE TITLE
CSP: Timeline violates CSP in regenerator/runtime.js

### ISSUE THREAD

**Issue by melloware** [visjs/vis-timeline#466]
Timeline is failing with Content Security Policy enabled for 2 reasons.

1. You are using "use strict" mode in your dist.

2. See this comment in Regenerator dependency:

https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js#L716-L728

Need to remove `use strict` from Babel: https://stackoverflow.com/questions/33821312/how-to-remove-global-use-strict-added-by-babel

Looks like it needs to fixed in vis-dev-utils:
https://github.com/visjs/vis-dev-utils/blob/master/babel-preset/index.js

**Comment by melloware** [comment]
I think this is fixed now with this PR: https://github.com/visjs/vis-timeline/pull/483

**Comment by yotamberk** [comment]
Indeed.
