### ISSUE TITLE
Wrong items behavior when timeline used within React layout 

### ISSUE THREAD

**Issue by leefsmp** [visjs/vis-timeline#495]
I would like to use the timeline inside [react-reflex](https://github.com/leefsmp/re-flex) (a React resizable layout) where on the top I have some 3d model and on the bottom a container for the timeline.

When inserted inside that layout (a flex layout), the timeline items start to behave funny, 2 issues I can spot:

1/ Items will disappear too early when shifted to the left, like if the container was smaller than it actually is.

![Screen Shot 2020-05-22 at 08 43 26](https://user-images.githubusercontent.com/4352502/82639201-8b5caf00-9c08-11ea-8825-9501c9115d71.png)

2/ more annoying, the items position is not correct when the time scale is being zoomed in or out. The correct date/time location will start to be correct only when zoomed very close.

<img width="597" alt="Screen Shot 2020-05-22 at 08 46 23" src="https://user-images.githubusercontent.com/4352502/82639423-fad29e80-9c08-11ea-9d7f-6b8a8972180f.png">

(Items showing nearby 2030)

<img width="533" alt="Screen Shot 2020-05-22 at 08 46 47" src="https://user-images.githubusercontent.com/4352502/82639433-032ad980-9c09-11ea-94c3-91575af9d4d4.png">

(With more zoom it's more 2016. Should be 2014...)

Here is the reproducible demo: https://codepen.io/leefsmp/pen/oNjmpja

Is this a CSS issue or some other problem the way I wrapped the timeline in the React component? 

I've used hundreds of other components within that resizable layout and never experienced trouble with it.

**Comment by leefsmp** [comment]
I found out that setting `text-align: left;` would just solve my issue. Would be great if it was part of the lib CSS by default as it seems quite important to have it this way.

```
.vis-timeline {
    text-align: left;
}
```

**Comment by reinismu** [comment]
Damn good thing I found this. Spent too much time trying to figure out why my things don't align
