### ISSUE TITLE
DataSet difference: vis-timeline/standalone VS vis-data

### ISSUE THREAD

**Issue by duckyb** [visjs/vis-timeline#510]
## Issue
First of all, this issue is related to `vis-timeline` but probably more to `vis-data` so I apologize if I should have posted it on it's issue tracker but it seemed quite less active.

The issue I have is that **when using the peer build, the DataSet constructor does not build the correct object**, while the standalone DataSet constructor does.

## Reproduction:

https://codesandbox.io/s/vis-peer-build-ebokh?file=/src/index.js

Comment lines `2-3` and uncomment line `6` to compare
Edit: If the timeline doesn't load the first time, just _reload the browser panel_

## DataSet diff
![img](https://i.imgur.com/5pwWQwi.png)

The version from `vis-data` shows an empty timeline, the version from `vis-timeline/standalone` populates the timeline with the correct data.

**Comment by Thomaash** [comment]
Hi @duckyb,

there is an error in the examples, the builds you use have to match:
```typescript
import { Timeline } from "vis-timeline/peer";
import { DataSet } from "vis-data/peer";
```

**Comment by duckyb** [comment]
Oh ok, makes sense. Thanks for fixing the docs
