### ISSUE TITLE
Clustering algorithm issue & potencial correction

### ISSUE THREAD

**Issue by tiperes** [visjs/vis-timeline#511]
Regarding timeline component, I've identified a bug in the cluster algorithm.

The cluster procedure seems to works ok when clusterCriteria function is not supplied.
Using the clusterCriteria function to build specific cluster the issue raises.

I've identified the issue in the ClusterGenerator class, getClusters function, line 157 of the last release version (#7.3.6).
Instead of "if (clusterCriteria(items[**m**].data, items[m].data))" is should be "if (clusterCriteria(items[**i**].data, items[m].data))".

With this fix, all seems to run ok.

Continue the great job!
Thanks.

**Comment by lmdc45** [comment]
Thanks a lot ! Spent quite some time on this one. Working fine with the fix above.

**Comment by lmdc45** [comment]
Also had an issue in 'isVisble' from clusterItem.js, added in
#532
