### ISSUE TITLE
extend instead of replace existing locales

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-timeline#55]
It is possible to set custom locales ([docs](https://visjs.github.io/vis-timeline/docs/timeline/#Localization), [example](https://github.com/visjs/vis-timeline/blob/1239015fef8ba73f9a887eef300d7d456d59ba53/examples/timeline/other/localizationCustom.html)).

### Current behavior

If a custom local is given the embedded locales are overwritten and can not be used anymore.

### Expected behavior

If custom locales are provided via the options the should extend the existing locals not replace them.

**Comment by exoego** [comment]
For future contributors:
A technique used https://github.com/visjs/vis-timeline/pull/88#discussion_r324438603 might be needed.
