### ISSUE TITLE
vis-timeline not as performant as timeline-plus

### ISSUE THREAD

**Issue by jczacharia** [visjs/vis-timeline#56]
Since deprecation of timeline-plus and its merge into the vis-timeline repo, I ported my project to use this repo, but I am experiencing major performance issues that are not present in timeline-plus. 

My project containing about 100 groups and each group around 10-20 nodes. I have all my groups load asynchronously such that the UI is not blocked when loading the groups. Using timeline-plus, each group takes around a quarter of a second to load, no problems once everything is loaded into memory; the UI is as smooth as butter. With vis-timeline, the first 10 groups take the same time but after that, each one group dramatically needs more time. The 100th group can take almost a minute to load. Then once everything is loaded, navigating around the timeline is severely laggy. I would say unusable. 

With timeline-plus, the timeline's UI is like butter. But unusable with this repo. I am concerned that the performance improvements made in timeline-plus were not correctly ported over to this timeline.

**Comment by mojoaxel** [comment]
We haven't released the Timeline-Plus merge. This will come with v6. Please try again after the next major release and let us know. Thanks!

**Comment by jczacharia** [comment]
Closing this. I am now seeing this repo as more performant.
