### ISSUE TITLE
vis-timeline@7.3.7 requires a peer of uuid@^3.4.0 || ^7.0.0

### ISSUE THREAD

**Issue by gregid** [visjs/vis-timeline#585]
Currently npm warns about uuid if the version installed is `^8.0.0`.
I propose it should be brought up to date and use the same dependency versions as in `vis-network`
`"uuid": "^3.4.0 || ^7.0.0 || ^8.0.0",`

**Comment by jdehaan** [comment]
See also https://github.com/visjs/vis-timeline/pull/456 (automatic bot upgrade)
The changes are not so big, I think actually the bot upgrade PR should be ok. I could not see issues (no deep requires used and I spotted only 4 places with `import { v4 as randomUUID } from "uuid";`)

**Comment by dennissterzenbach** [comment]
I think this has been fixed in #1016
