### ISSUE TITLE
Question in nested group

### ISSUE THREAD

**Issue by rafaelgfirmino** [visjs/vis-timeline#596]
Hi, I can try add a  edit and delete button in a nested group, but when i click in button the event resize is callend. 
![Screenshot (3)](https://user-images.githubusercontent.com/5332773/89146624-add54780-d52a-11ea-8459-e8f8833504b7.png)

how can i stop this behavior?

**Comment by yotamberk** [comment]
`e.stopPropagation()` should work on your buttons
