### ISSUE TITLE
postinstall script

### ISSUE THREAD

**Issue by mgobishop** [visjs/vis-timeline#6]
When I npm install vis-timeline I get the following error:

npm ERR! Failed at the vis-data@6.1.0 postinstall script

Any help or advice appreciated :-)

**Comment by UnicornDeluxe** [comment]
I got the same error and it seems to be the same problem I already reported for [vis-charts](https://github.com/visjs/vis-charts), somehow the [issue](https://github.com/visjs/vis-charts/issues/3) is not longer available.
Here is the fix again tho: https://github.com/react-native-training/react-native-elements/commit/e009574b99406642c451b0bc2f665f612d03f6fb

**Comment by UnicornDeluxe** [comment]
> 
> 
> When I npm install vis-timeline I get the following error:
> 
> npm ERR! Failed at the vis-data@6.1.0 postinstall script
> 
> Any help or advice appreciated :-)

As quick work around you can try to clone the repo and build it yourself:

> To build the library from source, clone the project from github
> 
> $ git clone git://github.com/visjs/vis-timeline.git
> 
> The source code uses the module style of node (require and module.exports) to organize dependencies. To install all dependencies and build the library, run npm install in the root of the project.
> 
> $ cd vis-timeline
> $ npm install
> 
> Then, the project can be build running:
> 
> $ npm run build

**Comment by mgobishop** [comment]
Thanks for the response! I agree that both timeline and network have the fix. It looks to me as thought the problem is with vis-data. The package.json in vis-data has the postinstall fix you mention in master but not in 6.1.0. Timeline and network both depend on 6.1.0. How you are able to install vis-network puzzles me though so maybe I am wrong? I can't install either!
