### ISSUE TITLE
rollingMode.follow doesn't work with setCurrentTime

### ISSUE THREAD

**Issue by bhdr1** [visjs/vis-timeline#607]
I set the current date to three hours ago and rollingMode.follow to true. The red line is in the right place but the center of timeline does not show the red line, showing still date now. How can achive this?

```
rollingMode: {
    follow: true,
    offset: 0.5
}

timeline.setCurrentTime(30 seconds ago)
```

Date now example - https://codepen.io/pen/?template=jOqWmpj

Set current time to 30 seconds example - https://codepen.io/pen/?template=eYZJWQJ

**Comment by yotamberk** [comment]
I don;t understand what you are trying to do. You want that the timeline will roll with an offset of 3 hours?

**Comment by reinismu** [comment]
@bhdr1 Hey! Did you manage to solve this? I find it super weird as well that rolling mode doesn't follow timelines set current mode, but just real time...

**Comment by bhdr1** [comment]
> @bhdr1 Hey! Did you manage to solve this? I find it super weird as well that rolling mode doesn't follow timelines set current mode, but just real time...

Unfortunately, I didn't solve this

**Comment by IgorA100** [comment]
This problem still exists, unfortunately...

**Comment by vpmartin** [comment]
Currently implementing a Timeline in a context where there can be replays of data from the past weeks or months. `setCurrentTime` works perfectly, given that my app knows the "current time" (i.e. replay time, whether it be real current time, 1 week ago, 3 months ago...).

`rollingMode `is a much needed feature to keep track of real-time events, even during past replays.

Doing `setCurrentTime `at initialization works, and the red line is shown at the time of the data in the past. It progresses as time goes by.

However, setting `rollingMode.follow = true` makes the timeline roll centered **at the current browser time**, and not at the red line set in the past. I would expect it to roll centered at the red line.

@yotamberk Any idea? Cheers.
