### ISSUE TITLE
Npm not up to date

### ISSUE THREAD

**Issue by theoarmengou** [visjs/vis-timeline#61]
Hello,

The npm package and the git have differents update dates but they have the same version :
`npm package` from : https://unpkg.com/vis-timeline@latest/dist/vis-timeline-graph2d.min.js
(Redirects to : https://unpkg.com/vis-timeline@5.1.0/dist/vis-timeline-graph2d.min.js)
```
 * @version 5.1.0
 * @date    2019-08-02T15:25:33Z
```

`git repo` from : https://github.com/visjs/vis-timeline/blob/master/dist/vis-timeline-graph2d.min.js
```
 * @version 5.1.0
 * @date    2019-08-13T18:10:02Z
```

The main problem is that in the `npm package` there is no such thing as **clustering** but in the `git repo`, the clustering is working correctly.

<details>
  <summary>Console error when clustering with using npm package</summary>

Here is the options used in the component:

  ```javascript
		// Configuration for the Timeline
		var defaultOptions = {
			stack: false,
			maxHeight: 800,
			height: 150,
			type: 'point',
			groupOrder: 'content',
			cluster: {
				titleTemplate:
					'This cluster contains {count} elements',
				showStipes: false
			},
			template: (itemData, element, data) => {
				if (data.isCluster) {
					return `<div>${data.content}</div>`;
				} else {
					return `<div>${data.content}</div>`;
				}
			},
			moment: function(date) {
				return vis.moment(date).utc();
			}
		};
  ```
And here is the error I get :
```
Unknown option detected: "cluster" in 

options = {
  cluster
}

Perhaps it was misplaced? Matching option found at: 
options = {
  configure: {
    filter
  }
}
```
</details>

Could you update the npm package along with the updates on the git repository or at least keep a version on npm that can run all the examples that can be found in : https://github.com/visjs/vis-timeline/tree/master/examples/

Thank you and keep going your library is very nice :1st_place_medal:

**Comment by mojoaxel** [comment]
@theoarmengou Please wait for the next release or use the github version for now!
