### ISSUE TITLE
The official example about locale does not work

### ISSUE THREAD

**Issue by AlanBrown1** [visjs/vis-timeline#62]
Thanks for creating such a powerful timeline util!, but when I use it to change locale by setOptions() function, it seems not working. And then, I find your official example as the follow link:**https://visjs.github.io/vis-timeline/examples/timeline/other/localization.html**, it also has the same problem in chrome and safari browser.

I'am wondering how could I change locale correctly. Looking forward to your answers, thx.

**Comment by pgrunewald** [comment]
I can confirm this bug. It is currently broken.

**Comment by mojoaxel** [comment]
closing as duplicate of #48
