### ISSUE TITLE
The sourcemap url in vis-timeline-graph2d.css is incorrect

### ISSUE THREAD

**Issue by gregid** [visjs/vis-timeline#621]
Current sourcemap url in `vis-timeline-graph2d.css` is:
```
/*# sourceMappingURL=styles/vis-timeline-graph2d.css.map */
```
while both files are in the same folder, so it should be:
```
/*# sourceMappingURL=vis-timeline-graph2d.css.map */
```
This is causing problems with bundlers, e.g.:
https://github.com/parcel-bundler/parcel/issues/5031

BTW The min file has correct url.

**Comment by Thomaash** [comment]
This is a bug in PostCSS plugin: https://github.com/egoist/rollup-plugin-postcss/pull/274, it should be fixed there.

**Comment by Thomaash** [comment]
We'll track this issue from https://github.com/visjs/vis-dev-utils/issues/294 as that's where the build process is maintained.
