### ISSUE TITLE
Is it possible to draw lines between two time difference? Attached screenshot for reference

### ISSUE THREAD

**Issue by nagaraj-nataraj** [visjs/vis-timeline#678]
<img width="471" alt="Capture" src="https://user-images.githubusercontent.com/71488884/93571358-f5684380-f9b1-11ea-8c7a-a260260c66a9.PNG">

**Comment by yotamberk** [comment]
you can use the `format` option to pass a template that has divs of lines spaced with css left by percentages.
(if you want 3 lines after the minor label, you add a div with height 5px, width 1px and left of 25%, 50% and 75%)

`function format({
  minorLabels: Function(date: Date, scale: Number, step: Number),
  majorLabels: Function(date: Date, scale: Number, step: Number)
`
