### ISSUE TITLE
locale settings

### ISSUE THREAD

**Issue by ajesses** [visjs/vis-timeline#687]
Hi,I want to set the locale to Chinese. how to set it?

**Comment by yotamberk** [comment]
https://visjs.github.io/vis-timeline/examples/timeline/other/localizationCustom.html

**Comment by ajesses** [comment]
It doesn't work when i locale to Chinese. And i read this file, it is not support!
[https://github.com/visjs/vis-timeline/blob/master/lib/timeline/locales.js](https://github.com/visjs/vis-timeline/blob/master/lib/timeline/locales.js)

**Comment by YouWillBe** [comment]
> Hi, @yotamberk
> It doesn't work when i locale to Chinese. And i read this file, it is not support!
> https://github.com/visjs/vis-timeline/blob/master/lib/timeline/locales.js

传locale进去貌似不起作用，不过我发现可以这样做
```javascript
import moment from 'moment'
import 'moment/locale/zh-cn'

moment.locale('zh-cn')

const options = {
    moment: moment,
}
```

**Comment by ajesses** [comment]
> > Hi, @yotamberk
> > It doesn't work when i locale to Chinese. And i read this file, it is not support!
> > https://github.com/visjs/vis-timeline/blob/master/lib/timeline/locales.js
> 
> 传locale进去貌似不起作用，不过我发现可以这样做
> 
> ```js
> import moment from 'moment'
> import 'moment/locale/zh-cn'
> 
> moment.locale('zh-cn')
> 
> const options = {
>     moment: moment,
> }
> ```

谢大佬，可以了

**Comment by ajesses** [comment]
解决

**Comment by YouWillBe** [comment]
> > > Hi, @yotamberk
> > > It doesn't work when i locale to Chinese. And i read this file, it is not support!
> > > https://github.com/visjs/vis-timeline/blob/master/lib/timeline/locales.js
> > 
> > 
> > 传locale进去貌似不起作用，不过我发现可以这样做
> > ```js
> > import moment from 'moment'
> > import 'moment/locale/zh-cn'
> > 
> > moment.locale('zh-cn')
> > 
> > const options = {
> >     moment: moment,
> > }
> > ```
> 
> 谢大佬，可以了

客气了，我也是在前段时间用到这个，试着摸索的
