### ISSUE TITLE
Question in nested group

### ISSUE THREAD

**Issue by rafaelgfirmino** [visjs/vis-timeline#702]
This issue is reopned #596

Hi, I can try to add the edit and delete button in a nested group, but when I click in button the event resize is called
![89146624-add54780-d52a-11ea-8459-e8f8833504b7](https://user-images.githubusercontent.com/5332773/95085189-4176f000-06f5-11eb-98f3-cb5904d2500a.png)

how can I stop this behavior?

````js
data:() => ({
    options: {
      ...
      groupTemplate: function(group){
      ...
        btnDelete.addEventListener("click", async (e) => {
          await group.removeAgendaEvent();
          E.stopPropagation();
          return false;
        });
      }
    }
})

**Comment by yotamberk** [comment]
Can you add a jsbin?
