### ISSUE TITLE
toArray issue IE11. Babel not working.

### ISSUE THREAD

**Issue by frankdevryer** [visjs/vis-timeline#72]
I'm getting the following error in IE11. I tried to convert it with babel but same error. Is this known and does someone have a fix? Cheers! 

![gantissue](https://user-images.githubusercontent.com/54716318/64030909-bfa6b180-cb47-11e9-8bc2-7c0a407e1099.PNG)

**Comment by yotamberk** [comment]
Can you supply a full example? 
It seems that your `this.items` is not an object.

**Comment by frankdevryer** [comment]
> Can you supply a full example?
> It seems that your `this.items` is not an object (I don;t think it's specifically a IE11 problem).

@yotamberk I think it is tho. I just checked the example pages of VIS and getting the same error as mine. https://visjs.github.io/vis-timeline/examples/timeline/basicUsage.html

**Comment by yotamberk** [comment]
Eh... I guess you force me to download IE11... Fine... The things I do for you guys... 😝

**Comment by melloware** [comment]
Is it some kind of IE polyfill issue with the `To.ToArray` call?

**Comment by mojoaxel** [comment]
This problems are caused by `vis-util`. (see https://github.com/visjs/vis-util/issues/59)

**Comment by jasonex7** [comment]
I see problems in calls to Object.assign, Object.values, etc. Those functions are not present in IE11 so you can use babel/runtime to include those polyfills. I test PR #100 and it works on IE11 🎉
