### ISSUE TITLE
Show the time between two adjacent items

### ISSUE THREAD

**Issue by clasit** [visjs/vis-timeline#743]
I would like to show the time between two adjacent items (as shows the image).
I didn't found a feature to solve this. In your opinion, what could be a good way to obtain this result?

Thanks.

<img width="640" alt="time_slots" src="https://user-images.githubusercontent.com/5436761/96704578-8e64f280-1394-11eb-8835-585d907e9d8d.png">

**Comment by razbensimon** [comment]
add yourself "gaps" as items and style them differently.

**Comment by yotamberk** [comment]
@razbensimon is right. That is the right way to do it!
