### ISSUE TITLE
Package compatibility w/ Yarn

### ISSUE THREAD

**Issue by j-calvert** [visjs/vis-timeline#748]
I'm trying to use vis-timeline within an environment that requires use of Yarn.

When I `yarn add --dev vis-timeline` it complains about missing the peer dependency vis-data.

If I `yarn add --dev vis-timeline vis-data` the install succeeds, but the timeline UI component malfunctions as in  https://photos.app.goo.gl/7fz7kUYUWZKB2LAF8 (the items slide around in time when one zooms in and out).

I _**think**_ others might have run into the same problem in https://github.com/visjs/vis-timeline/issues/312 and https://github.com/visjs/vis-timeline/issues/510 , and if that's the case, maybe my problem is that I'm mixing standalone and peer 'builds' of vis-timeline and vis-data.

Honestly, I'm not even sure how to tell which 'build' of vis-timeline I'm grabbing with the yarn add.  It looks like the peer build, so maybe this issue I'm encountering has nothing to do with DataSet incompatibility with Timeline.

Hoping this weird behavior looks familiar to someone that might be able to shed some light on how to fix it.

My package.json lines
```
        "vis-data": "^7.1.0",
        "vis-timeline": "^7.4.0",
```
My yarn.lock lines
```
vis-data@^7.1.0:
  version "7.1.0"
  resolved "https://registry.yarnpkg.com/vis-data/-/vis-data-7.1.0.tgz#022dc2c4a9afa64c85b59c7465a20e3bdd32a51a"

vis-timeline@^7.4.0:
  version "7.4.0"
  resolved "https://registry.yarnpkg.com/vis-timeline/-/vis-timeline-7.4.0.tgz#65e95d580d446a080fe54c432fff247ddc44ebc0"
```

Thanks!

**Comment by yotamberk** [comment]
installing the packages don't install a specific build. It's how you import the library is what counts.
`import { Timeline } from "vis-timeline/peer";`
or 
`import { Timeline } from "vis-timeline/esnext";`
or 
`import { Timeline } from "vis-timeline/standalone";`

**Comment by j-calvert** [comment]
I see.  Is this what might be referred to as a "dynamic import"?  If so, I think that my problem might be that these aren't really handled by my org's third party js system.

**Comment by j-calvert** [comment]
I've actually ruled out my theory that DataSet & TimeLine build incompatibilities is causing problems.  Standard yarn install gives me peer build and it works fine.  My issues are related to something else.  Marking resolved.
