### ISSUE TITLE
Dynamic Attributes on events

### ISSUE THREAD

**Issue by carloszan** [visjs/vis-timeline#75]
Hi,

Is there a way to pass an attribute to item so I can get it on an event? 
I mean, in my project, I have to check if an item is a boolean value or not but when I added a listener to check that, an obj has some default properties but no dynamic properties.

I added a click event with on method like so:

```
timeline.on('click', (e) => {
      console.log(e)
 })
```

I want to know or suggest that could be possible to add dynamic properties to events so it could be possible to handle every item click.

Thanks and regards

**Comment by yotamberk** [comment]
Well, you do get info clicking on the timeline when an item is clicked.
See https://visjs.github.io/vis-timeline/examples/timeline/interaction/eventListeners.html
Clicking an item gives you:
``` json
{"event":{"isTrusted":true},"item":4,"isCluster":false,"items":[],"group":null,"what":"item","pageX":347,"pageY":88,"x":339,"y":20,"time":"2013-04-17T01:42:51.428Z","snappedTime":"2013-04-16T21:00:00.000Z"}
```
Which then allows you to reach the item data via its id.
