### ISSUE TITLE
doc: add doc example for range type

### ISSUE THREAD

**Issue by Grummfy** [visjs/vis-timeline#773]
hi,
regarding visjs timeline,
in the documentation we find that the type of an item can be 

> The type of the item. Can be 'box' (default), 'point', 'range', or 'background'. Types 'box' and 'point' need a start date, the types 'range' and 'background' needs both a start and end date. 

But I didn't see an example for range. Could you add one?

thanks

**Comment by yotamberk** [comment]
https://visjs.github.io/vis-timeline/examples/timeline/interaction/sequentialSelection.html

**Comment by Grummfy** [comment]
I don't see any mention of range, it's only "background"

**Comment by yotamberk** [comment]
The moment you define an item with an "end", it is taken as a ranged item
