### ISSUE TITLE
Ability to move the red slider in desired time

### ISSUE THREAD

**Issue by ajinra020307** [visjs/vis-timeline#782]
I am using vis-timeline for my project. vis-timeline by default have the red line moving as current time. Is there any way to drag the red slider and move it to any time.

Thank You

**Comment by dennissterzenbach** [comment]
Actually this is something you can solve with some CSS + JavaScript.

1. You just need to get the element from the DOM. Which you can do using `document.querySelector('.vis-current-time')`

2. Then make sure the browser will fire events when users interact with the current time bar:
```css
.vis-current-time {
  pointer-events: all;
}
```
You need to make sure that specificity for the selector makes the browser override the default style.

or you store the element into a variable and set that style using JavaScript: `currentTimeElem.style.pointerEvents = 'all';`

3. then you can simply hook your own native JavaScript event handler to it:
`currentTimeElem.addEventListener('click', () => { window.alert('user clicked on current time'); });`

Here's a codepen which demonstrates that:
https://codepen.io/dennissterzenbach/pen/QWdzORq/left/?editors=0010
