### ISSUE TITLE
Composer unable to install vis-timeline as NPM asset

### ISSUE THREAD

**Issue by LetsIncreaseThatKnowledge** [visjs/vis-timeline#79]
After adding the NPM package to my composer file (require > "vis-timeline": "5.1.0"). composer is unable to find it. However it does find the vis-network NPM package. Composer search cannot find it either, it only returns "cliffparnitzky/vis.js-timeline". Am I the only one experiencing this issue?

**Comment by mojoaxel** [comment]
visjs dos not support composer.
Also vis-network is not supported by composer: https://packagist.org/?query=vis-network

**Comment by NickvdMeij** [comment]
Got the same problem here. Using the https://github.com/fxpio/composer-asset-plugin for loading npm packages with composer. All vis packages install properly except vis-timeline

**Comment by mojoaxel** [comment]
@NickvdMeij Thanks for that helpful comment. We don't support composer but I see no reason why an installation via npm should not work.

**Comment by NickvdMeij** [comment]
@mojoaxel yeah its strange. Tried to install it earlier and for some reason it installs correctly with npm, but using the asset-packagist, it doesnt seem to install through composer. All other visjs packages install correctly this way, so my guess is that it has something to do with this package? Atm im installing it with composer using the git repo as artifact as workaround

**Comment by mojoaxel** [comment]
I just testes the npm install. It works for 5.1.0.
So this is propably a problem with asset-packagist?

> Atm im installing it with composer using the git repo as artifact as workaround

We have a big new release (v6) comming up.
Please use the already releases version v5.1 from npm.

Please try to find more error information if you can!

**Comment by LetsIncreaseThatKnowledge** [comment]
@mojoaxel propably is since vis-network has no issues. Using the workaround @NickvdMeij mentioned.    oddly asset-packagist.org does return vis-timeline as a "ready to use" package.

**Comment by yotamberk** [comment]
Can we try this again now that v6 is out? Is this still an issue?

**Comment by yotamberk** [comment]
Composer will not be supported in our projects. 
Closing this issue unless future work will require this ability.

**Comment by mojoaxel** [comment]
I just tested it and everything seams to work:
https://asset-packagist.org/package/npm-asset/vis-timeline
