### ISSUE TITLE
[build] ReferenceError: window is not defined on hammerjs 

### ISSUE THREAD

**Issue by exoego** [visjs/vis-timeline#87]
I cannot run test after `npm install` completed successfully. 

```
$> npm run test

> vis-timeline@0.0.0-no-version test /home/vagrant/IdeaProjects/vis-timeline
> mocha --exit --require @babel/register

/home/vagrant/IdeaProjects/vis-timeline/node_modules/hammerjs/hammer.js:2643
})(window, document, 'Hammer');
   ^
ReferenceError: window is not defined
```

* npm version : 6.11.2
* nodejs version: 10.16.2

I can run `npm run dist` and it build successfully.

#### Related issue:
* https://github.com/hammerjs/hammer.js/issues/930
* https://github.com/hammerjs/hammer.js/issues/1060

**Comment by mojoaxel** [comment]
I can confirm this bug in the test setup.

**Comment by mojoaxel** [comment]
Maybe @Thomaash can help!?

**Comment by Thomaash** [comment]
Replacing hammerjs with @egjs/hammerjs solves this issue. We already did this in Vis Network.
