### ISSUE TITLE
Template function returns html, the html is then stripped of it's class

### ISSUE THREAD

**Issue by Steveiwonder** [visjs/vis-timeline#888]
While testing this library I found an issue which seems odd.
I tested this as my template function

```
template: function(item, element, data){
  let html =  `<h6><i class="${item.icon}"></i>${item.content}</h6>`;
  console.log(html);
  return html;
}
}
```

The class from the `i` element is removed once it's returned, i can see in the console the html output is correct

![image](https://user-images.githubusercontent.com/1899448/105576077-3a3d2600-5d68-11eb-9a82-b5d897709f70.png)

but this is the elements in the dom
![image](https://user-images.githubusercontent.com/1899448/105576094-550f9a80-5d68-11eb-91ff-7c1da34a35e5.png)

EDIT:

After some debugging it looks like a call to `util.xss(content)` strips the class

Thanks

Steve

**Comment by YoannChabert** [comment]
see #846

**Comment by mojoaxel** [comment]
Let's close this as a dublicate of #846
