### ISSUE TITLE
Not rendering fontawesome icons

### ISSUE THREAD

**Issue by dgil-unedbarbastro** [visjs/vis-timeline#956]
Hi, I've noticed that font-awesome icons inside the items content (e.g. `<i class="fas fa-chess-queen"></i>`) are rendered correctly for the version 4.3.12 and below, but for more recent version they are not rendered at all, just removes the class and ends being `<i></i>` .

You can check those cases here:

- [Example using v7.3.12](https://jsfiddle.net/danielgil/ujwg9kep/1/) (working)
- [Example using v7.4.6](https://jsfiddle.net/danielgil/pzj3e52y/17/) (not working)

**Comment by mojoaxel** [comment]
Looks like this is caused by #840

**Comment by dgil-unedbarbastro** [comment]
you are welcome.... happy to help  :)
